// Generated by scripts/build-cities.ps1 from GeoNames (https://www.geonames.org, CC BY 4.0):
// each country's capital plus its 10 largest other cities. Same format as PLACE_LINES in places.js,
// which takes priority when a name appears in both. Edit places.js by hand; regenerate this file.
const CITY_LINES = `
Kabul|Afghanistan|34.528|69.172
Herāt;Herat|Afghanistan|34.348|62.2
Kandahār;Kandahar|Afghanistan|31.613|65.71
Mazār-e Sharīf;Mazar-e Sharif|Afghanistan|36.709|67.111
Jalālābād;Jalalabad|Afghanistan|34.426|70.452
Kunduz|Afghanistan|36.729|68.857
Ghazni|Afghanistan|33.554|68.421
Balkh|Afghanistan|36.756|66.897
Bagrām;Bagram|Afghanistan|34.967|69.265
Baghlān;Baghlan|Afghanistan|36.131|68.708
Gardez|Afghanistan|33.597|69.226
Mariehamn|Aland Islands|60.097|19.935
Tirana|Albania|41.327|19.819
Durrës;Durres|Albania|41.324|19.455
Vlorë;Vlore|Albania|40.47|19.484
Elbasan|Albania|41.111|20.082
Shkodër;Shkoder|Albania|42.068|19.513
Lushnjë;Lushnje|Albania|40.942|19.705
Berat|Albania|40.706|19.952
Korçë;Korce|Albania|40.619|20.781
Fier|Albania|40.725|19.558
Krujë;Kruje|Albania|41.509|19.793
Pogradec|Albania|40.902|20.652
Algiers|Algeria|36.732|3.087
Oran|Algeria|35.699|-0.636
Annaba|Algeria|36.9|7.767
Blida|Algeria|36.47|2.828
Batna|Algeria|35.556|6.174
Bab Ezzouar|Algeria|36.726|3.183
Djelfa|Algeria|34.673|3.263
Sétif;Setif|Algeria|36.191|5.414
Sidi Bel Abbes|Algeria|35.19|-0.631
Biskra|Algeria|34.85|5.728
Pago Pago|American Samoa|-14.278|-170.702
Andorra la Vella|Andorra|42.508|1.521
les Escaldes|Andorra|42.507|1.534
Luanda|Angola|-8.837|13.234
Mulenvos|Angola|-8.867|13.334
Viana|Angola|-8.906|13.375
Kikolo|Angola|-8.782|13.334
Maianga|Angola|-8.847|13.237
Camama|Angola|-8.936|13.265
Calumbo|Angola|-9.147|13.419
Hoji ya Henda|Angola|-8.805|13.29
Lubango|Angola|-14.917|13.492
Huambo|Angola|-12.776|15.739
Buenos Aires|Argentina|-34.613|-58.377
Córdoba;Cordoba|Argentina|-31.406|-64.189
Rosario|Argentina|-32.947|-60.639
Mar del Plata|Argentina|-38|-57.556
San Miguel de Tucumán;San Miguel de Tucuman|Argentina|-26.816|-65.211
Salta|Argentina|-24.806|-65.42
Avellaneda|Argentina|-34.66|-58.367
Corrientes|Argentina|-27.468|-58.834
Posadas|Argentina|-27.392|-55.924
Bahía Blanca;Bahia Blanca|Argentina|-38.718|-62.265
Yerevan|Armenia|40.178|44.513
Gyumri|Armenia|40.793|43.846
Vanadzor|Armenia|40.807|44.497
Abovyan|Armenia|40.272|44.633
Hrazdan|Armenia|40.517|44.756
Vagharshapat|Armenia|40.166|44.295
Kapan|Armenia|39.208|46.407
Armavir|Armenia|40.156|44.039
Masis|Armenia|40.066|44.437
Artashat|Armenia|39.955|44.549
Charentsavan|Armenia|40.403|44.644
Oranjestad|Aruba|12.524|-70.027
Tanki Leendert|Aruba|12.539|-70.02
Sydney|Australia|-33.868|151.207
Melbourne|Australia|-37.814|144.963
Brisbane|Australia|-27.468|153.028
Perth|Australia|-31.952|115.861
Adelaide|Australia|-34.929|138.599
Gold Coast|Australia|-28|153.431
Sunshine Coast|Australia|-26.657|153.08
Canberra|Australia|-35.283|149.128
Logan City|Australia|-27.639|153.109
Vienna|Austria|48.208|16.372
Graz|Austria|47.067|15.442
Linz|Austria|48.306|14.286
Salzburg|Austria|47.799|13.044
Innsbruck|Austria|47.263|11.395
Klagenfurt am Wörthersee;Klagenfurt am Woerthersee|Austria|46.625|14.305
Villach|Austria|46.61|13.856
Eisenzicken|Austria|47.276|16.259
Dornbirn|Austria|47.414|9.742
Wiener Neustadt|Austria|47.805|16.232
Steyr|Austria|48.043|14.421
Baku|Azerbaijan|40.378|49.892
Sumgayit|Azerbaijan|40.59|49.669
Ganja|Azerbaijan|40.682|46.361
Khirdalan|Azerbaijan|40.448|49.755
Yevlakh|Azerbaijan|40.618|47.15
Mingachevir|Azerbaijan|40.764|47.062
Naxçıvan;Naxcivan|Azerbaijan|39.209|45.412
Lankaran|Azerbaijan|38.754|48.851
Qaraçuxur;Qaracuxur|Azerbaijan|40.397|49.974
Lerik|Azerbaijan|38.774|48.415
Şirvan;Sirvan|Azerbaijan|39.938|48.929
Nassau|Bahamas|25.058|-77.343
Lucaya|Bahamas|26.533|-78.667
Al Muharraq|Bahrain|26.257|50.612
Manama|Bahrain|26.228|50.586
Madīnat Ḩamad;Madinat Hamad|Bahrain|26.115|50.507
Ar Rifā‘;Ar Rifa'|Bahrain|26.13|50.555
Sitrah|Bahrain|26.155|50.621
Jidd Ḩafş;Jidd Hafs|Bahrain|26.219|50.548
Dār Kulayb;Dar Kulayb|Bahrain|26.069|50.504
Madīnat ‘Īsá;Madinat 'Isa|Bahrain|26.174|50.548
Dhaka|Bangladesh|23.71|90.407
Chattogram|Bangladesh|22.338|91.832
Gazipur|Bangladesh|23.998|90.422
Khulna|Bangladesh|22.81|89.564
Rangpur|Bangladesh|25.747|89.252
Rajshahi|Bangladesh|24.374|88.601
Comilla|Bangladesh|23.462|91.185
Mohammadpur|Bangladesh|24.898|88.528
Hāthazāri;Hathazari|Bangladesh|22.505|91.813
Shibganj|Bangladesh|25.001|89.323
Natore|Bangladesh|24.411|88.987
Bridgetown|Barbados|13.107|-59.62
Minsk|Belarus|53.9|27.567
Homyel'|Belarus|52.434|30.975
Hrodna|Belarus|53.676|23.829
Vitebsk|Belarus|55.19|30.205
Mahilyow|Belarus|53.909|30.34
Brest|Belarus|52.109|23.717
Bobruysk|Belarus|53.147|29.205
Baranovichi|Belarus|53.133|26.008
Barysaw|Belarus|54.228|28.505
Pinsk|Belarus|52.122|26.067
Mazyr|Belarus|52.042|29.216
Brussels|Belgium|50.85|4.349
Antwerp|Belgium|51.22|4.4
Gent|Belgium|51.05|3.717
Charleroi|Belgium|50.411|4.444
Liège;Liege|Belgium|50.634|5.567
Anderlecht|Belgium|50.836|4.315
Schaerbeek|Belgium|50.869|4.377
Brugge|Belgium|51.209|3.224
Namur|Belgium|50.467|4.867
Leuven|Belgium|50.88|4.701
Molenbeek-Saint-Jean|Belgium|50.85|4.312
Belize City|Belize|17.5|-88.198
Orange Walk|Belize|18.081|-88.563
Belmopan|Belize|17.254|-88.764
Cotonou|Benin|6.365|2.418
Abomey-Calavi|Benin|6.449|2.356
Porto-Novo|Benin|6.496|2.604
Parakou|Benin|9.337|2.63
Godomè;Godome|Benin|6.389|2.346
Abomey|Benin|7.183|1.991
Djougou|Benin|9.709|1.666
Bohicon|Benin|7.178|2.067
Ekpé;Ekpe|Benin|6.392|2.537
Malanville|Benin|11.868|3.383
Thimphu|Bhutan|27.466|89.642
Phuntsholing|Bhutan|26.852|89.388
Tsirang|Bhutan|27.022|90.123
Punākha;Punakha|Bhutan|27.591|89.877
La Paz|Bolivia|-16.5|-68.15
Santa Cruz de la Sierra|Bolivia|-17.786|-63.181
Cochabamba|Bolivia|-17.382|-66.16
Sucre|Bolivia|-19.033|-65.263
Oruro|Bolivia|-17.972|-67.093
Sacaba|Bolivia|-17.398|-66.038
Quillacollo|Bolivia|-17.392|-66.278
Tarija|Bolivia|-21.535|-64.73
Potosí;Potosi|Bolivia|-19.584|-65.753
Riberalta|Bolivia|-11.01|-66.053
Kralendijk|Bonaire, Saint Eustatius and Saba |12.15|-68.267
Sarajevo|Bosnia|43.849|18.356
Banja Luka|Bosnia|44.779|17.206
Zenica|Bosnia|44.202|17.904
Tuzla|Bosnia|44.538|18.667
Mostar|Bosnia|43.343|17.808
Bihać;Bihac|Bosnia|44.817|15.871
Ilidža;Ilidza|Bosnia|43.831|18.307
Lukavac|Bosnia|44.542|18.526
Bugojno|Bosnia|44.057|17.451
Brčko;Brcko|Bosnia|44.872|18.816
Bijeljina|Bosnia|44.759|19.214
Gaborone|Botswana|-24.655|25.909
Francistown|Botswana|-21.17|27.508
Mogoditshane|Botswana|-24.627|25.866
Maun|Botswana|-19.983|23.417
Molepolole|Botswana|-24.407|25.495
Serowe|Botswana|-22.388|26.711
Tlokweng|Botswana|-24.669|25.971
Palapye|Botswana|-22.546|27.125
Mochudi|Botswana|-24.417|26.15
Mahalapye|Botswana|-23.104|26.814
São Paulo;Sao Paulo|Brazil|-23.548|-46.636
Rio de Janeiro|Brazil|-22.906|-43.182
Belo Horizonte|Brazil|-19.921|-43.938
Salvador|Brazil|-12.976|-38.491
Fortaleza|Brazil|-3.717|-38.543
Manaus|Brazil|-3.102|-60.025
Brasília;Brasilia|Brazil|-15.78|-47.93
Curitiba|Brazil|-25.428|-49.273
Recife|Brazil|-8.054|-34.881
Goiânia;Goiania|Brazil|-16.679|-49.254
Belém;Belem|Brazil|-1.456|-48.504
Road Town|British Virgin Islands|18.427|-64.621
Bandar Seri Begawan|Brunei|4.89|114.94
Sengkurong|Brunei|4.883|114.833
Mentiri|Brunei|4.971|115.021
Kuala Belait|Brunei|4.584|114.231
Tutong|Brunei|4.803|114.649
Serasa|Brunei|5.018|115.058
Sofia|Bulgaria|42.698|23.324
Plovdiv|Bulgaria|42.154|24.75
Varna|Bulgaria|43.219|27.91
Burgas|Bulgaria|42.507|27.469
Stara Zagora|Bulgaria|42.432|25.643
Ruse|Bulgaria|43.849|25.953
Pleven|Bulgaria|43.418|24.617
Sliven|Bulgaria|42.686|26.326
Pernik|Bulgaria|42.597|23.033
Shumen|Bulgaria|43.271|26.923
Dobrich|Bulgaria|43.565|27.831
Ouagadougou|Burkina Faso|12.366|-1.534
Bobo-Dioulasso|Burkina Faso|11.181|-4.295
Koudougou|Burkina Faso|12.252|-2.367
Saaba|Burkina Faso|12.371|-1.415
Ouahigouya|Burkina Faso|13.577|-2.418
Banfora|Burkina Faso|10.641|-4.753
Pouytenga|Burkina Faso|12.252|-0.426
Houndé;Hounde|Burkina Faso|11.5|-3.517
Fada N'gourma|Burkina Faso|12.062|0.358
Nioko I|Burkina Faso|12.395|-1.439
Bujumbura|Burundi|-3.382|29.361
Gitega|Burundi|-3.427|29.925
Ngozi|Burundi|-2.908|29.831
Mpanda|Burundi|-3.17|29.403
Rumonge|Burundi|-3.974|29.439
Cibitoke|Burundi|-2.887|29.125
Kayanza|Burundi|-2.922|29.629
Cendajuru|Burundi|-3.289|30.601
Bubanza|Burundi|-3.08|29.391
Vyanda|Burundi|-4.102|29.606
Zanandore|Burundi|-3.255|30.114
Praia|Cabo Verde|14.932|-23.513
Mindelo|Cabo Verde|16.89|-24.98
Espargos|Cabo Verde|16.755|-22.945
Assomada|Cabo Verde|15.1|-23.683
Phnom Penh|Cambodia|11.562|104.916
Takeo|Cambodia|10.991|104.785
Siem Reap|Cambodia|13.362|103.861
Battambang|Cambodia|13.103|103.198
Paoy Paet|Cambodia|13.658|102.564
Dangkao|Cambodia|11.509|104.891
Kampong Chhnang|Cambodia|12.25|104.667
Sihanoukville|Cambodia|10.609|103.53
Preaek Prasab|Cambodia|12.354|106.036
Kampong Cham|Cambodia|11.993|105.464
Anlong Veaeng|Cambodia|14.232|104.081
Douala|Cameroon|4.048|9.704
Yaoundé;Yaounde|Cameroon|3.867|11.517
Bamenda|Cameroon|5.96|10.146
Bafoussam|Cameroon|5.478|10.418
Maroua|Cameroon|10.591|14.316
Ngaoundéré;Ngaoundere|Cameroon|7.328|13.585
Kumba|Cameroon|4.636|9.447
Nkongsamba|Cameroon|4.955|9.94
Buea|Cameroon|4.153|9.242
Kousséri;Kousseri|Cameroon|12.077|15.031
Bertoua|Cameroon|4.577|13.685
Toronto|Canada|43.706|-79.399
Montréal;Montreal|Canada|45.509|-73.588
Calgary|Canada|51.05|-114.085
Ottawa|Canada|45.411|-75.698
Edmonton|Canada|53.55|-113.469
Winnipeg|Canada|49.884|-97.147
Mississauga|Canada|43.579|-79.658
Vancouver|Canada|49.25|-123.119
Brampton|Canada|43.683|-79.766
George Town|Cayman Islands|19.287|-81.374
Bangui|Central African Republic|4.361|18.555
Bégoua;Begoua|Central African Republic|4.454|18.535
Berbérati;Berberati|Central African Republic|4.261|15.792
Bambari|Central African Republic|5.768|20.676
Bouar|Central African Republic|5.934|15.596
Bossangoa|Central African Republic|6.493|17.455
Kaga-Bandoro|Central African Republic|6.99|19.187
Bangassou|Central African Republic|4.741|22.818
Paoua|Central African Republic|7.243|16.441
N'Djamena|Chad|12.107|15.044
Moundou|Chad|8.574|16.077
Abéché;Abeche|Chad|13.829|20.832
Sarh|Chad|9.146|18.383
Kelo|Chad|9.309|15.807
Am Timan|Chad|11.043|20.283
Doba|Chad|8.664|16.853
Bongor|Chad|10.281|15.374
Goz Beida|Chad|12.226|21.41
Koumra|Chad|8.916|17.55
Santiago|Chile|-33.457|-70.648
Puente Alto|Chile|-33.612|-70.576
Maipú;Maipu|Chile|-33.514|-70.765
Antofagasta|Chile|-23.651|-70.398
Viña del Mar;Vina del Mar|Chile|-33.025|-71.552
Valparaíso;Valparaiso|Chile|-33.036|-71.63
San Bernardo|Chile|-33.592|-70.7
Puerto Montt|Chile|-41.469|-72.942
Arica|Chile|-18.476|-70.301
Peñalolén;Penalolen|Chile|-33.468|-70.534
Temuco|Chile|-38.736|-72.597
Shanghai|China|31.222|121.458
Chongqing|China|29.56|106.558
Chengdu|China|30.667|104.067
Beijing|China|39.908|116.397
Guangzhou|China|23.117|113.25
Shenzhen|China|22.546|114.068
Tianjin|China|39.142|117.177
Wuhan|China|30.583|114.267
Xi’an;Xi'an|China|34.258|108.929
Hangzhou|China|30.294|120.161
Harbin|China|45.75|126.65
Flying Fish Cove|Christmas Island|-10.422|105.679
Bogotá;Bogota|Colombia|4.61|-74.082
Cali|Colombia|3.431|-76.52
Medellín;Medellin|Colombia|6.245|-75.572
Barranquilla|Colombia|10.969|-74.781
Cartagena|Colombia|10.398|-75.493
Cúcuta;Cucuta|Colombia|7.907|-72.505
Soacha|Colombia|4.579|-74.217
Bucaramanga|Colombia|7.125|-73.119
Ibagué;Ibague|Colombia|4.436|-75.203
Santa Marta|Colombia|11.239|-74.194
Montería;Monteria|Colombia|8.751|-75.878
Moroni|Comoros|-11.702|43.255
Moutsamoudou|Comoros|-12.167|44.399
Fomboni|Comoros|-12.288|43.743
Brazzaville|Congo|-4.266|15.283
Pointe-Noire|Congo|-4.776|11.864
Dolisie|Congo|-4.198|12.667
Nkayi|Congo|-4.184|13.286
Impfondo|Congo|1.618|18.06
Ouesso|Congo|1.614|16.052
Owando|Congo|-0.482|15.9
Sibiti|Congo|-3.682|13.35
Loutété;Loutete|Congo|-4.296|13.851
Bouansa|Congo|-4.219|13.762
Avarua|Cook Islands|-21.208|-159.775
San José;San Jose|Costa Rica|9.934|-84.085
Limón;Limon|Costa Rica|9.991|-83.036
Alajuela|Costa Rica|10.017|-84.213
Puntarenas|Costa Rica|9.977|-84.838
Curridabat|Costa Rica|9.914|-84.036
San Vicente de Moravia|Costa Rica|9.962|-84.049
Zagreb|Croatia|45.814|15.978
Rijeka|Croatia|45.327|14.442
Osijek|Croatia|45.551|18.694
Zadar|Croatia|44.116|15.225
Sesvete|Croatia|45.831|16.116
Pula|Croatia|44.868|13.848
Slavonski Brod|Croatia|45.162|18.016
Karlovac|Croatia|45.492|15.55
Varaždin;Varazdin|Croatia|46.304|16.338
Šibenik;Sibenik|Croatia|43.734|15.894
Havana|Cuba|23.133|-82.383
Santiago de Cuba|Cuba|20.023|-75.822
Camagüey;Camagueey|Cuba|21.381|-77.917
Holguín;Holguin|Cuba|20.887|-76.263
Guantánamo;Guantanamo|Cuba|20.144|-75.209
Arroyo Naranjo|Cuba|23.038|-82.377
Las Tunas|Cuba|20.961|-76.952
Bayamo|Cuba|20.374|-76.643
Pinar del Río;Pinar del Rio|Cuba|22.416|-83.697
Cienfuegos|Cuba|22.147|-80.448
Willemstad|Curacao|12.122|-68.886
Bandariba|Curacao|12.093|-68.831
Nicosia|Cyprus|35.173|33.354
Limassol|Cyprus|34.684|33.038
Larnaca|Cyprus|34.922|33.628
Stróvolos;Strovolos|Cyprus|35.149|33.334
Famagusta|Cyprus|35.125|33.941
Káto Lakatámeia;Kato Lakatameia|Cyprus|35.118|33.325
Paphos|Cyprus|34.777|32.425
Kyrenia|Cyprus|35.336|33.317
Mórfou;Morfou|Cyprus|35.199|32.993
Káto Polemídia;Kato Polemidia|Cyprus|34.697|32.993
Aradíppou;Aradippou|Cyprus|34.948|33.588
Prague|Czechia|50.088|14.421
Brno|Czechia|49.195|16.608
Ostrava|Czechia|49.835|18.282
Pilsen|Czechia|49.747|13.378
Liberec|Czechia|50.767|15.056
Olomouc|Czechia|49.596|17.252
České Budějovice;Ceske Budejovice|Czechia|48.974|14.474
Hradec Králové;Hradec Kralove|Czechia|50.209|15.833
Ústí nad Labem;Usti nad Labem|Czechia|50.661|14.032
Pardubice|Czechia|50.041|15.777
Brno střed;Brno stred|Czechia|49.193|16.607
Copenhagen|Denmark|55.676|12.566
Århus;Arhus|Denmark|56.157|10.211
Odense|Denmark|55.396|10.388
Aalborg|Denmark|57.048|9.919
Frederiksberg|Denmark|55.679|12.535
Esbjerg|Denmark|55.47|8.452
Randers|Denmark|56.461|10.036
Kolding|Denmark|55.49|9.472
Horsens|Denmark|55.861|9.85
Vejle|Denmark|55.709|9.536
Hvidovre|Denmark|55.643|12.477
Balbala|Djibouti|11.562|43.107
Ali Sabih|Djibouti|11.156|42.712
Dikhil|Djibouti|11.105|42.37
Tadjoura|Djibouti|11.788|42.882
Arta|Djibouti|11.526|42.852
Obock|Djibouti|11.967|43.288
Roseau|Dominica|15.302|-61.388
Santo Domingo|Dominican Republic|18.472|-69.892
Santiago de los Caballeros|Dominican Republic|19.45|-70.691
Santo Domingo Oeste|Dominican Republic|18.5|-70
Santo Domingo Este|Dominican Republic|18.485|-69.848
San Pedro de Macorís;San Pedro de Macoris|Dominican Republic|18.454|-69.309
La Romana|Dominican Republic|18.423|-68.966
San Cristóbal;San Cristobal|Dominican Republic|18.417|-70.107
Puerto Plata|Dominican Republic|19.793|-70.688
San Francisco de Macorís;San Francisco de Macoris|Dominican Republic|19.294|-70.253
Salvaleón de Higüey;Salvaleon de Higueey|Dominican Republic|18.615|-68.708
La Vega|Dominican Republic|19.22|-70.531
Kinshasa|DR Congo|-4.328|15.314
Lubumbashi|DR Congo|-11.661|27.479
Mbuji-Mayi|DR Congo|-6.136|23.59
Kisangani|DR Congo|0.515|25.191
Kananga|DR Congo|-5.896|22.417
Bukavu|DR Congo|-2.491|28.843
Kolwezi|DR Congo|-10.715|25.467
Likasi|DR Congo|-10.983|26.738
Tshikapa|DR Congo|-6.416|20.8
Kikwit|DR Congo|-5.041|18.816
Masina|DR Congo|-4.384|15.391
Quito|Ecuador|-0.23|-78.525
Guayaquil|Ecuador|-2.196|-79.886
Cuenca|Ecuador|-2.895|-78.996
Santo Domingo de los Colorados|Ecuador|-0.254|-79.176
Ambato|Ecuador|-1.249|-78.617
Portoviejo|Ecuador|-1.058|-80.451
Eloy Alfaro|Ecuador|-2.169|-79.84
Machala|Ecuador|-3.259|-79.959
Loja|Ecuador|-3.993|-79.204
Manta|Ecuador|-0.949|-80.731
Riobamba|Ecuador|-1.665|-78.659
Cairo|Egypt|30.063|31.25
Alexandria|Egypt|31.202|29.916
Giza|Egypt|30.009|31.209
Shubrā al Khaymah;Shubra al Khaymah|Egypt|30.125|31.251
Port Said|Egypt|31.265|32.302
Suez|Egypt|29.974|32.526
Al Mansurah|Egypt|31.036|31.381
Al Maḩallah al Kubrá;Al Mahallah al Kubra|Egypt|30.971|31.167
Tanta|Egypt|30.788|31.002
Assiut|Egypt|27.181|31.184
Al Fayyum|Egypt|29.31|30.842
San Salvador|El Salvador|13.689|-89.187
Soyapango|El Salvador|13.71|-89.14
Mejicanos|El Salvador|13.724|-89.188
Santa Tecla|El Salvador|13.677|-89.283
Apopa|El Salvador|13.807|-89.179
Sonsonate|El Salvador|13.717|-89.723
Usulután;Usulutan|El Salvador|13.345|-88.44
Bata|Equatorial Guinea|1.864|9.766
Malabo|Equatorial Guinea|3.756|8.782
Ebebiyin|Equatorial Guinea|2.152|11.33
Añisoc;Anisoc|Equatorial Guinea|1.866|10.769
Aconibe|Equatorial Guinea|1.297|10.937
Ciudad de la Paz|Equatorial Guinea|1.592|10.824
Asmara|Eritrea|15.338|38.932
Keren|Eritrea|15.778|38.451
Himora|Eritrea|14.304|36.606
Af’abet;Af'abet|Eritrea|16.188|38.687
Massawa|Eritrea|15.608|39.475
Assab|Eritrea|13.009|42.739
Mendefera|Eritrea|14.887|38.815
Barentu|Eritrea|15.106|37.591
Tallinn|Estonia|59.437|24.754
Tartu|Estonia|58.381|26.725
Narva|Estonia|59.377|28.19
Pärnu;Paernu|Estonia|58.386|24.497
Kohtla-Järve;Kohtla-Jaerve|Estonia|59.399|27.273
Viljandi|Estonia|58.363|25.592
Maardu|Estonia|59.465|24.982
Manzini|Eswatini|-26.499|31.38
Mbabane|Eswatini|-26.317|31.133
Lobamba|Eswatini|-26.467|31.2
Addis Ababa|Ethiopia|9.025|38.747
Jijiga|Ethiopia|9.35|42.8
Gonder|Ethiopia|12.6|37.467
Mek'ele|Ethiopia|13.497|39.475
Nazrēt;Nazret|Ethiopia|8.55|39.267
Warder|Ethiopia|6.974|45.341
Awasa|Ethiopia|7.062|38.476
Bahir Dar|Ethiopia|11.594|37.391
Dire Dawa|Ethiopia|9.593|41.866
Dessie|Ethiopia|11.133|39.633
Jimma|Ethiopia|7.673|36.834
Tórshavn;Torshavn|Faroe Islands|62.01|-6.772
Nasinu|Fiji|-18.071|178.513
Suva|Fiji|-18.137|178.425
Lautoka|Fiji|-17.617|177.45
Nadi|Fiji|-17.803|177.416
Labasa|Fiji|-16.433|179.365
Lami|Fiji|-18.111|178.409
Sigatoka|Fiji|-18.143|177.507
Helsinki|Finland|60.17|24.935
Espoo|Finland|60.205|24.652
Tampere|Finland|61.499|23.787
Vantaa|Finland|60.294|25.041
Oulu|Finland|65.012|25.468
Turku|Finland|60.451|22.269
Jyväskylä;Jyvaeskylae|Finland|62.241|25.721
Kuopio|Finland|62.892|27.677
Lahti|Finland|60.983|25.662
Pori|Finland|61.481|21.785
Joensuu|Finland|62.601|29.763
Paris|France|48.853|2.349
Marseille|France|43.297|5.381
Lyon|France|45.749|4.848
Toulouse|France|43.604|1.444
Nantes|France|47.217|-1.553
Marne La Vallée;Marne La Vallee|France|48.836|2.642
Strasbourg|France|48.584|7.746
Bordeaux|France|44.841|-0.58
Montpellier|France|43.611|3.876
Lille|France|50.634|3.055
Cayenne|French Guiana|4.938|-52.335
Matoury|French Guiana|4.849|-52.324
Saint-Laurent-du-Maroni|French Guiana|5.502|-54.029
Kourou|French Guiana|5.163|-52.643
Rémire-Montjoly;Remire-Montjoly|French Guiana|4.917|-52.267
Faaa|French Polynesia|-17.559|-149.604
Papeete|French Polynesia|-17.535|-149.568
Punaauia|French Polynesia|-17.633|-149.6
Port-aux-Français;Port-aux-Francais|French Southern Territories|-49.349|70.219
Libreville|Gabon|0.392|9.454
Port-Gentil|Gabon|-0.719|8.782
Franceville|Gabon|-1.633|13.584
Owendo|Gabon|0.291|9.505
Oyem|Gabon|1.6|11.579
Moanda|Gabon|-1.567|13.199
Ntoum|Gabon|0.391|9.761
Lambaréné;Lambarene|Gabon|-0.7|10.241
Mouila|Gabon|-1.868|11.056
Akanda|Gabon|0.607|9.329
Tchibanga|Gabon|-2.933|10.982
Serekunda|Gambia|13.438|-16.678
Brikama|Gambia|13.271|-16.649
Sukuta|Gambia|13.41|-16.708
Talinding|Gambia|13.426|-16.673
Faji Kunda|Gambia|13.418|-16.667
Bakau|Gambia|13.478|-16.682
Banjul|Gambia|13.453|-16.578
Nema Kunku|Gambia|13.25|-15.883
Farafenni|Gambia|13.567|-15.6
Busumbala|Gambia|13.339|-16.688
Tbilisi|Georgia|41.691|44.834
Batumi|Georgia|41.641|41.631
Kutaisi|Georgia|42.268|42.695
Rustavi|Georgia|41.563|44.979
Sokhumi|Georgia|43.007|40.989
Gori|Georgia|41.985|44.113
Poti|Georgia|42.143|41.674
Zugdidi|Georgia|42.508|41.868
Ts’khinvali;Ts'khinvali|Georgia|42.228|43.969
Stantsiya Novyy Afon|Georgia|43.081|40.838
Marneuli|Georgia|41.488|44.798
Berlin|Germany|52.524|13.411
Hamburg|Germany|53.551|9.993
Munich|Germany|48.137|11.575
Köln;Koeln|Germany|50.933|6.95
Frankfurt am Main|Germany|50.116|8.684
Düsseldorf;Duesseldorf|Germany|51.223|6.779
Stuttgart|Germany|48.782|9.177
Essen|Germany|51.457|7.012
Dortmund|Germany|51.515|7.466
Dresden|Germany|51.051|13.738
Bremen|Germany|53.076|8.807
Kumasi|Ghana|6.688|-1.624
Accra|Ghana|5.556|-0.197
Tamale|Ghana|9.401|-0.839
Takoradi|Ghana|4.898|-1.76
Sekondi|Ghana|4.934|-1.715
Cape Coast|Ghana|5.105|-1.247
Atsiaman|Ghana|5.698|-0.328
Ashaiman|Ghana|5.7|-0.035
Obuase|Ghana|6.202|-1.668
Tema|Ghana|5.67|-0.017
Koforidua|Ghana|6.094|-0.259
Athens|Greece|37.984|23.728
Thessaloníki;Thessaloniki|Greece|40.641|22.935
Pátra;Patra|Greece|38.246|21.735
Piraeus|Greece|37.942|23.646
Lárisa;Larisa|Greece|39.628|22.421
Peristéri;Peristeri|Greece|38.015|23.692
Irákleion;Irakleion|Greece|35.328|25.143
Kallithéa;Kallithea|Greece|37.95|23.7
Acharnés;Acharnes|Greece|38.083|23.733
Kalamariá;Kalamaria|Greece|40.582|22.95
Níkaia;Nikaia|Greece|37.967|23.65
Nuuk|Greenland|64.183|-51.722
Saint George's|Grenada|12.053|-61.752
Les Abymes|Guadeloupe|16.273|-61.505
Baie-Mahault|Guadeloupe|16.267|-61.585
Le Gosier|Guadeloupe|16.206|-61.493
Petit-Bourg|Guadeloupe|16.192|-61.591
Le Moule|Guadeloupe|16.332|-61.347
Capesterre-Belle-Eau|Guadeloupe|16.045|-61.564
Pointe-à-Pitre;Pointe-a-Pitre|Guadeloupe|16.236|-61.535
Basse-Terre|Guadeloupe|15.997|-61.732
Dededo Village|Guam|13.518|144.839
Yigo Village|Guam|13.536|144.889
Tamuning-Tumon-Harmon Village|Guam|13.488|144.781
Mangilao Village|Guam|13.448|144.801
Hagåtña;Hagatna|Guam|13.476|144.749
Guatemala City|Guatemala|14.641|-90.513
Villa Nueva|Guatemala|14.525|-90.585
Mixco|Guatemala|14.631|-90.607
Cobán;Coban|Guatemala|15.47|-90.375
Quetzaltenango|Guatemala|14.845|-91.523
Jalapa|Guatemala|14.635|-89.991
Escuintla|Guatemala|14.301|-90.788
Villa Canales|Guatemala|14.483|-90.534
Jutiapa|Guatemala|14.285|-89.888
Chichicastenango|Guatemala|14.943|-91.111
San Juan Sacatepéquez;San Juan Sacatepequez|Guatemala|14.719|-90.644
Saint Peter Port|Guernsey|49.46|-2.535
Conakry|Guinea|9.538|-13.677
Camayenne|Guinea|9.535|-13.688
Nzérékoré;Nzerekore|Guinea|7.756|-8.818
Kankan|Guinea|10.385|-9.306
Manéah;Maneah|Guinea|9.733|-13.417
Dixinn|Guinea|9.551|-13.673
Dubréka;Dubreka|Guinea|9.791|-13.523
Kindia|Guinea|10.057|-12.866
Siguiri|Guinea|11.423|-9.169
Kamsar|Guinea|10.65|-14.617
Kissidougou|Guinea|9.185|-10.1
Bissau|Guinea-Bissau|11.864|-15.598
Gabú;Gabu|Guinea-Bissau|12.28|-14.222
Contumo|Guinea-Bissau|11.85|-15.617
Reino de Bandim|Guinea-Bissau|11.85|-15.6
Bafatá;Bafata|Guinea-Bissau|12.166|-14.662
Reino de Antula|Guinea-Bissau|11.9|-15.583
Quelele|Guinea-Bissau|11.867|-15.633
Xitole|Guinea-Bissau|11.733|-14.817
Georgetown|Guyana|6.804|-58.155
New Amsterdam|Guyana|6.249|-57.516
Port-au-Prince|Haiti|18.543|-72.339
Delmas|Haiti|18.545|-72.3
Pétionville;Petionville|Haiti|18.512|-72.285
Port-de-Paix|Haiti|19.94|-72.83
Saint-Marc|Haiti|19.111|-72.701
Cité Soleil;Cite Soleil|Haiti|18.58|-72.338
Croix-des-Bouquets|Haiti|18.577|-72.226
Dessalines|Haiti|19.262|-72.516
Jacmel|Haiti|18.236|-72.537
Cap-Haïtien;Cap-Haitien|Haiti|19.759|-72.198
Tegucigalpa|Honduras|14.082|-87.207
San Pedro Sula|Honduras|15.506|-88.026
Danlí;Danli|Honduras|14.033|-86.583
La Ceiba|Honduras|15.76|-86.782
Puerto Cortez|Honduras|15.826|-87.93
Catacamas|Honduras|14.851|-85.894
Choloma|Honduras|15.614|-87.953
Siguatepeque|Honduras|14.597|-87.831
Olanchito|Honduras|15.481|-86.574
Tocoa|Honduras|15.683|-86
Tuen Mun|Hong Kong|22.392|113.972
Sha Tin|Hong Kong|22.383|114.183
Sham Shui Po|Hong Kong|22.33|114.159
Wong Tai Sin|Hong Kong|22.35|114.183
Kowloon City|Hong Kong|22.33|114.192
Tseung Kwan O|Hong Kong|22.328|114.25
Kwai Chung|Hong Kong|22.368|114.139
Tsuen Wan|Hong Kong|22.371|114.113
Tin Shui Wai|Hong Kong|22.457|114.002
Budapest|Hungary|47.498|19.04
Debrecen|Hungary|47.532|21.624
Szeged|Hungary|46.253|20.148
Miskolc|Hungary|48.103|20.778
Pécs;Pecs|Hungary|46.076|18.228
Győr;Gyor|Hungary|47.683|17.635
Nyíregyháza;Nyiregyhaza|Hungary|47.955|21.717
Kecskemét;Kecskemet|Hungary|46.906|19.691
Székesfehérvár;Szekesfehervar|Hungary|47.19|18.41
Szombathely|Hungary|47.231|16.622
Szolnok|Hungary|47.181|20.198
Reykjavík;Reykjavik|Iceland|64.135|-21.895
Kópavogur;Kopavogur|Iceland|64.112|-21.913
Hafnarfjörður;Hafnarfjoerdur|Iceland|64.067|-21.938
Reykjanesbær|Iceland|63.998|-22.561
Akureyri|Iceland|65.684|-18.088
Keflavík;Keflavik|Iceland|64.005|-22.562
Mumbai|India|19.073|72.883
Delhi|India|28.652|77.231
Bengaluru|India|12.972|77.594
Hyderabad|India|17.384|78.456
Ahmedabad|India|23.026|72.587
Chennai|India|13.088|80.278
Kolkata|India|22.563|88.363
Surat|India|21.196|72.83
Pune|India|18.52|73.855
Jaipur|India|26.92|75.788
New Delhi|India|28.621|77.215
Jakarta|Indonesia|-6.215|106.845
Surabaya|Indonesia|-7.249|112.751
Bekasi|Indonesia|-6.235|106.99
Bandung|Indonesia|-6.922|107.607
Medan|Indonesia|3.583|98.667
Depok|Indonesia|-6.4|106.819
Tangerang|Indonesia|-6.178|106.63
Palembang|Indonesia|-2.917|104.746
Semarang|Indonesia|-6.993|110.421
Makassar|Indonesia|-5.149|119.432
South Tangerang|Indonesia|-6.289|106.718
Tehran|Iran|35.694|51.422
Mashhad|Iran|36.298|59.606
Isfahan|Iran|32.652|51.675
Karaj|Iran|35.833|50.992
Tabriz|Iran|38.08|46.292
Shiraz|Iran|29.61|52.531
Qom|Iran|34.64|50.876
Ahvaz|Iran|31.319|48.684
Kermanshah|Iran|34.314|47.065
Rasht|Iran|37.276|49.589
Kerman|Iran|30.283|57.079
Baghdad|Iraq|33.341|44.401
Mosul|Iraq|36.335|43.119
Erbil|Iraq|36.191|44.009
Basrah|Iraq|30.509|47.78
Karbala|Iraq|32.616|44.025
Sadr City|Iraq|33.389|44.458
Kirkuk|Iraq|35.468|44.392
Abū Ghurayb;Abu Ghurayb|Iraq|33.306|44.185
Sulaymaniyah|Iraq|35.565|45.433
Nasiriyah|Iraq|31.058|46.257
Najaf|Iraq|32.026|44.346
Dublin|Ireland|53.333|-6.249
Cork|Ireland|51.898|-8.471
Limerick|Ireland|52.665|-8.623
Galway|Ireland|53.272|-9.051
Tallaght|Ireland|53.286|-6.373
Waterford|Ireland|52.258|-7.112
Drogheda|Ireland|53.719|-6.348
Dundalk|Ireland|54|-6.417
Navan|Ireland|53.653|-6.681
Jerusalem|Israel|31.769|35.216
Tel Aviv|Israel|32.081|34.781
Haifa|Israel|32.813|34.999
Rishon LeTsiyyon|Israel|31.971|34.789
Petaẖ Tiqva;Petah Tiqva|Israel|32.089|34.887
Netanya|Israel|32.333|34.859
Ashdod|Israel|31.792|34.65
Bnei Brak|Israel|32.081|34.834
H̱olon;Holon|Israel|32.01|34.779
Beersheba|Israel|31.252|34.791
Rome|Italy|41.892|12.511
Milan|Italy|45.464|9.19
Naples|Italy|40.852|14.268
Turin|Italy|45.07|7.687
Palermo|Italy|38.117|13.364
Genoa|Italy|44.405|8.944
Bologna|Italy|44.494|11.339
Florence|Italy|43.779|11.246
Bari|Italy|41.121|16.87
Catania|Italy|37.492|15.07
Verona|Italy|45.439|10.994
Abidjan|Ivory Coast|5.354|-4.002
Abobo|Ivory Coast|5.416|-4.016
Bouaké;Bouake|Ivory Coast|7.694|-5.03
Korhogo|Ivory Coast|9.458|-5.63
Daloa|Ivory Coast|6.877|-6.45
Koumassi|Ivory Coast|5.297|-3.968
San-Pédro;San-Pedro|Ivory Coast|4.749|-6.636
Gagnoa|Ivory Coast|6.132|-5.951
Yamoussoukro|Ivory Coast|6.821|-5.277
Sinfra|Ivory Coast|6.621|-5.911
Kingston|Jamaica|17.997|-76.794
Spanish Town|Jamaica|17.991|-76.957
Portmore|Jamaica|17.971|-76.887
Montego Bay|Jamaica|18.471|-77.919
Mandeville|Jamaica|18.042|-77.507
May Pen|Jamaica|17.965|-77.245
Ocho Rios|Jamaica|18.408|-77.103
Old Harbour|Jamaica|17.941|-77.109
Linstead|Jamaica|18.137|-77.032
Half Way Tree|Jamaica|18.012|-76.799
Barrett Town|Jamaica|18.515|-77.802
Tokyo|Japan|35.69|139.692
Yokohama|Japan|35.433|139.65
Osaka|Japan|34.694|135.501
Nagoya|Japan|35.181|136.906
Sapporo|Japan|43.067|141.35
Fukuoka|Japan|33.6|130.417
Kawasaki|Japan|35.521|139.717
Kobe|Japan|34.691|135.183
Kyoto|Japan|35.021|135.754
Saitama|Japan|35.908|139.657
Hiroshima|Japan|34.4|132.45
Saint Helier|Jersey|49.188|-2.105
Amman|Jordan|31.955|35.945
Zarqa|Jordan|32.073|36.088
Irbid|Jordan|32.556|35.85
Russeifa|Jordan|32.018|36.046
Khuraybat as Sūq;Khuraybat as Suq|Jordan|31.879|35.921
Wādī as Sīr;Wadi as Sir|Jordan|31.954|35.818
Ar Ramthā;Ar Ramtha|Jordan|32.559|36.008
Ṣuwayliḥ;Suwaylih|Jordan|32.022|35.844
‘Ajlūn;'Ajlun|Jordan|32.333|35.753
As Salţ;As Salt|Jordan|32.039|35.727
Aqaba|Jordan|29.527|35.008
Almaty|Kazakhstan|43.252|76.912
Astana|Kazakhstan|51.18|71.446
Shymkent|Kazakhstan|42.31|69.6
Aktobe|Kazakhstan|50.28|57.207
Karagandy|Kazakhstan|49.802|73.102
Taraz|Kazakhstan|42.898|71.373
Kyzylorda|Kazakhstan|44.853|65.509
Pavlodar|Kazakhstan|52.276|76.969
Ust-Kamenogorsk|Kazakhstan|49.971|82.606
Semey|Kazakhstan|50.421|80.25
Nairobi|Kenya|-1.283|36.817
Kakamega|Kenya|0.284|34.752
Mombasa|Kenya|-4.055|39.664
Nakuru|Kenya|-0.307|36.072
Ruiru|Kenya|-1.147|36.961
Eldoret|Kenya|0.52|35.27
Kisumu|Kenya|-0.102|34.762
Thika|Kenya|-1.033|37.069
Naivasha|Kenya|-0.714|36.433
Karuri|Kenya|-0.7|37.183
Tarawa|Kiribati|1.328|172.977
Pristina|Kosovo|42.673|21.167
Prizren|Kosovo|42.214|20.74
Mitrovicë;Mitrovice|Kosovo|42.883|20.867
Gjakovë;Gjakove|Kosovo|42.38|20.431
Suva Reka|Kosovo|42.359|20.825
Ferizaj|Kosovo|42.371|21.155
Glogovac|Kosovo|42.628|20.894
Gjilan|Kosovo|42.46|21.47
Deçan;Decan|Kosovo|42.54|20.288
Pejë;Peje|Kosovo|42.659|20.288
Vitina|Kosovo|42.321|21.358
Al Aḩmadī;Al Ahmadi|Kuwait|29.077|48.084
Ḩawallī;Hawalli|Kuwait|29.333|48.029
Şabāḩ as Sālim;Sabah as Salim|Kuwait|29.257|48.057
Al Farwānīyah;Al Farwaniyah|Kuwait|29.278|47.959
Al Faḩāḩīl;Al Fahahil|Kuwait|29.082|48.13
Kuwait City|Kuwait|29.367|47.974
Ar Riqqah|Kuwait|29.146|48.095
Al Manqaf|Kuwait|29.096|48.133
Al Jahrā’;Al Jahra'|Kuwait|29.338|47.658
Al Finţās;Al Fintas|Kuwait|29.174|48.121
Janūb as Surrah;Janub as Surrah|Kuwait|29.269|47.978
Bishkek|Kyrgyzstan|42.87|74.59
Osh|Kyrgyzstan|40.528|72.798
Manas|Kyrgyzstan|40.945|72.993
Karakol|Kyrgyzstan|42.49|78.392
Tokmok|Kyrgyzstan|42.842|75.301
Uzgen|Kyrgyzstan|40.77|73.301
Kara-Balta|Kyrgyzstan|42.814|73.848
Balykchy|Kyrgyzstan|42.46|76.187
Naryn|Kyrgyzstan|41.428|75.996
Bazar-Korgon|Kyrgyzstan|41.038|72.746
Talas|Kyrgyzstan|42.523|72.242
Vientiane|Laos|17.967|102.6
Savannakhet|Laos|16.57|104.762
Thakhèk;Thakhek|Laos|17.41|104.831
Pakse|Laos|15.12|105.799
Ban Khoan|Laos|20.35|100.09
Xam Nua|Laos|20.416|104.045
Luang Prabang|Laos|19.893|102.152
Muang Phônsavan;Muang Phonsavan|Laos|19.449|103.192
Ban Xénô;Ban Xeno|Laos|16.676|104.988
Muang Xay|Laos|20.692|101.984
Vang Vieng|Laos|18.924|102.448
Riga|Latvia|56.946|24.106
Daugavpils|Latvia|55.883|26.533
Liepāja;Liepaja|Latvia|56.505|21.011
Jelgava|Latvia|56.65|23.713
Jūrmala;Jurmala|Latvia|56.968|23.77
Ventspils|Latvia|57.395|21.561
Rēzekne;Rezekne|Latvia|56.51|27.34
Valmiera|Latvia|57.541|25.428
Jēkabpils;Jekabpils|Latvia|56.499|25.857
Mārupe;Marupe|Latvia|56.905|24.051
Beirut|Lebanon|33.893|35.502
Sidon|Lebanon|33.558|35.371
Tyre|Lebanon|33.273|35.194
Aley|Lebanon|33.805|35.6
Nabatîyé et Tahta;Nabatiye et Tahta|Lebanon|33.379|35.484
Habboûch;Habbouch|Lebanon|33.408|35.482
Jounieh|Lebanon|33.981|35.618
Zahlé;Zahle|Lebanon|33.847|35.902
Aarsâl;Aarsal|Lebanon|34.179|36.421
Ghazieh|Lebanon|33.518|35.369
Maseru|Lesotho|-29.317|27.483
Maputsoe|Lesotho|-28.887|27.899
Mohale's Hoek|Lesotho|-30.151|27.477
Mafeteng|Lesotho|-29.823|27.237
Hlotse|Lesotho|-28.872|28.045
Butha-Buthe|Lesotho|-28.767|28.249
Mabote|Lesotho|-29.279|27.524
Quthing|Lesotho|-30.4|27.7
Teyateyaneng|Lesotho|-29.147|27.749
Qacha’s Nek;Qacha's Nek|Lesotho|-30.115|28.689
Thaba-Tseka|Lesotho|-29.522|28.608
Monrovia|Liberia|6.301|-10.797
Gbarnga|Liberia|6.995|-9.471
Ganta|Liberia|7.235|-8.984
Kakata|Liberia|6.531|-10.354
Zwedru|Liberia|6.068|-8.136
Harbel|Liberia|6.247|-10.356
Pleebo City|Liberia|4.59|-7.672
Foya Kamara|Liberia|8.36|-10.206
New Yekepa|Liberia|7.579|-8.538
Tripoli|Libya|32.887|13.187
Benghazi|Libya|32.115|20.069
Misratah|Libya|32.375|15.093
Zliten|Libya|32.467|14.569
Al Khums|Libya|32.649|14.262
Az Zāwīyah;Az Zawiyah|Libya|32.757|12.728
Zawiya|Libya|32.752|12.728
Janzūr;Janzur|Libya|32.819|13.017
Sabha|Libya|27.038|14.428
Tobruk|Libya|32.09|23.954
Ajdabiya|Libya|30.755|20.226
Vaduz|Liechtenstein|47.142|9.522
Vilnius|Lithuania|54.689|25.28
Kaunas|Lithuania|54.902|23.909
Klaipėda;Klaipeda|Lithuania|55.707|21.139
Šiauliai;Siauliai|Lithuania|55.933|23.317
Panevėžys;Panevezys|Lithuania|55.732|24.36
Alytus|Lithuania|54.396|24.039
Marijampolė;Marijampole|Lithuania|54.558|23.35
Mazeikiai|Lithuania|56.317|22.333
Jonava|Lithuania|55.08|24.275
Utena|Lithuania|55.498|25.605
Kėdainiai;Kedainiai|Lithuania|55.288|23.973
Esch-sur-Alzette|Luxembourg|49.496|5.981
Dudelange|Luxembourg|49.481|6.088
Macau|Macao|22.201|113.546
Taipa|Macao|22.156|113.557
Luhuan|Macao|22.118|113.552
Zhuojiacun|Macao|22.161|113.556
Lai Chi Van|Macao|22.12|113.551
Antananarivo|Madagascar|-18.914|47.536
Toamasina|Madagascar|-18.149|49.402
Antsirabe|Madagascar|-19.866|47.033
Mahajanga|Madagascar|-15.717|46.317
Fianarantsoa|Madagascar|-21.453|47.086
Toliara|Madagascar|-23.35|43.667
Antsiranana|Madagascar|-12.317|49.292
Sambava|Madagascar|-14.267|50.167
Imerintsiatosika|Madagascar|-18.983|47.317
Antalaha|Madagascar|-14.9|50.279
Tôlanaro;Tolanaro|Madagascar|-25.032|46.983
Lilongwe|Malawi|-13.967|33.787
Blantyre|Malawi|-15.785|35.009
Mzuzu|Malawi|-11.466|34.021
Zomba|Malawi|-15.386|35.319
Karonga|Malawi|-9.933|33.933
Kasungu|Malawi|-13.033|33.483
Mangochi|Malawi|-14.478|35.264
Salima|Malawi|-13.78|34.459
Liwonde|Malawi|-15.067|35.225
Balaka|Malawi|-14.979|34.956
Dedza|Malawi|-14.378|34.333
Kuala Lumpur|Malaysia|3.141|101.687
Johor Bahru|Malaysia|1.466|103.758
Kampung Baru Subang|Malaysia|3.15|101.533
Petaling Jaya|Malaysia|3.107|101.607
Ipoh|Malaysia|4.584|101.083
Shah Alam|Malaysia|3.085|101.533
Bukit Rahman Putra|Malaysia|3.217|101.561
Pelentong|Malaysia|1.524|103.824
Malacca|Malaysia|2.196|102.24
Iskandar Puteri|Malaysia|1.393|103.623
Kota Bharu|Malaysia|6.124|102.243
Bamako|Mali|12.609|-7.975
Sikasso|Mali|11.318|-5.667
Koutiala|Mali|12.387|-5.465
Ségou;Segou|Mali|13.44|-6.259
Kayes|Mali|14.448|-11.444
Mopti|Mali|14.484|-4.183
Kalaban Koro|Mali|12.573|-8.029
Gao|Mali|16.272|-0.045
Bougouni|Mali|11.418|-7.483
San Pawl il-Baħar;San Pawl il-Bahar|Malta|35.951|14.416
Birkirkara|Malta|35.897|14.461
Mosta|Malta|35.909|14.426
Sliema|Malta|35.912|14.502
Qormi|Malta|35.876|14.472
Żabbar;Zabbar|Malta|35.877|14.536
Valletta|Malta|35.9|14.515
Majuro|Marshall Islands|7.09|171.38
Dalap-Uliga-Dorrit|Marshall Islands|7.087|171.377
Fort-de-France|Martinique|14.604|-61.074
Le Lamentin|Martinique|14.613|-61
Le Robert|Martinique|14.678|-60.942
Le François;Le Francois|Martinique|14.615|-60.903
Ducos|Martinique|14.575|-60.975
La Trinité;La Trinite|Martinique|14.738|-60.963
Nouakchott|Mauritania|18.086|-15.978
Nouadhibou|Mauritania|20.942|-17.038
Kiffa|Mauritania|16.621|-11.402
Dar Naim|Mauritania|18.108|-15.927
Néma;Nema|Mauritania|16.617|-7.256
Mbera|Mauritania|15.856|-5.791
Ksar|Mauritania|18.1|-15.957
Kaédi;Kaedi|Mauritania|16.151|-13.506
Zouérat;Zouerat|Mauritania|22.735|-12.471
Tevragh Zeina|Mauritania|18.099|-15.988
Bougadoum|Mauritania|15.867|-7.369
Port Louis|Mauritius|-20.162|57.499
Vacoas|Mauritius|-20.298|57.478
Beau Bassin-Rose Hill|Mauritius|-20.233|57.466
Curepipe|Mauritius|-20.316|57.526
Quatre Bornes|Mauritius|-20.264|57.479
Triolet|Mauritius|-20.058|57.55
Goodlands|Mauritius|-20.038|57.651
Bel Air Rivière Sèche;Bel Air Riviere Seche|Mauritius|-20.258|57.75
Bambous|Mauritius|-20.257|57.406
Centre de Flacq|Mauritius|-20.19|57.714
Mahébourg;Mahebourg|Mauritius|-20.408|57.7
Mamoudzou|Mayotte|-12.782|45.229
Koungou|Mayotte|-12.734|45.204
Labattoir|Mayotte|-12.777|45.282
Kaouéni;Kaoueni|Mayotte|-12.771|45.224
Dzaoudzi|Mayotte|-12.783|45.257
Mexico City|Mexico|19.428|-99.128
Tijuana|Mexico|32.503|-117.004
Iztapalapa|Mexico|19.355|-99.062
Puebla|Mexico|19.048|-98.207
Ecatepec de Morelos|Mexico|19.605|-99.061
Santiago de Querétaro;Santiago de Queretaro|Mexico|20.588|-100.388
León de los Aldama;Leon de los Aldama|Mexico|21.122|-101.683
Ciudad Juárez;Ciudad Juarez|Mexico|31.72|-106.461
Zapopan|Mexico|20.721|-103.387
Guadalajara|Mexico|20.677|-103.347
Mérida;Merida|Mexico|20.967|-89.623
Palikir|Micronesia|6.925|158.161
Chisinau|Moldova|47.009|28.859
Tiraspol|Moldova|46.843|29.628
Bălţi;Balti|Moldova|47.763|27.929
Rîbniţa;Ribnita|Moldova|47.768|29.01
Cahul|Moldova|45.905|28.195
Ungheni|Moldova|47.21|27.8
Soroca|Moldova|48.157|28.285
Durleşti;Durlesti|Moldova|47.022|28.763
Orhei|Moldova|47.385|28.825
Dubăsari;Dubasari|Moldova|47.266|29.167
Ulan Bator|Mongolia|47.908|106.883
Erdenet|Mongolia|49.033|104.083
Darhan|Mongolia|49.487|105.923
Choibalsan|Mongolia|48.073|114.533
Nalayh|Mongolia|47.767|107.283
Mörön;Moeroen|Mongolia|49.634|100.162
Bayanhongor|Mongolia|46.194|100.718
Ulaangom|Mongolia|49.981|92.067
Khovd|Mongolia|48.006|91.642
Arvayheer|Mongolia|46.264|102.775
Ölgii;OElgii|Mongolia|48.968|89.962
Podgorica|Montenegro|42.441|19.263
Nikšić;Niksic|Montenegro|42.773|18.944
Herceg Novi|Montenegro|42.453|18.538
Pljevlja|Montenegro|43.357|19.358
Budva|Montenegro|42.287|18.839
Bijelo Polje|Montenegro|43.038|19.748
Cetinje|Montenegro|42.391|18.914
Brades|Montserrat|16.792|-62.211
Casablanca|Morocco|33.588|-7.611
Rabat|Morocco|34.013|-6.833
Fes|Morocco|34.033|-5
Tangier|Morocco|35.767|-5.8
Marrakesh|Morocco|31.634|-8
Salé|Morocco|34.053|-6.798
Agadir|Morocco|30.42|-9.598
Meknes|Morocco|33.894|-5.547
Oujda|Morocco|34.681|-1.909
Kenitra|Morocco|34.261|-6.58
Tétouan;Tetouan|Morocco|35.578|-5.368
Maputo|Mozambique|-25.966|32.583
Matola|Mozambique|-25.962|32.459
Nampula|Mozambique|-15.116|39.267
Beira|Mozambique|-19.844|34.839
Chimoio|Mozambique|-19.116|33.483
Tete|Mozambique|-16.156|33.587
Quelimane|Mozambique|-17.879|36.888
Lichinga|Mozambique|-13.313|35.241
Nacala|Mozambique|-14.563|40.685
Pemba|Mozambique|-12.974|40.518
Mocuba|Mozambique|-16.838|36.986
Yangon|Myanmar|16.805|96.156
Mandalay|Myanmar|21.975|96.084
Nay Pyi Taw|Myanmar|19.745|96.13
Hlaingthaya|Myanmar|16.85|96.067
Mawlamyine|Myanmar|16.491|97.628
Kalemyo|Myanmar|23.19|94.064
Insein|Myanmar|16.889|96.103
Bago|Myanmar|17.335|96.481
Amarapura|Myanmar|21.907|96.049
Pathein|Myanmar|16.779|94.732
Yawnghwe|Myanmar|20.66|96.934
Windhoek|Namibia|-22.559|17.083
Rundu|Namibia|-17.918|19.773
Walvis Bay|Namibia|-22.958|14.505
Swakopmund|Namibia|-22.678|14.527
Oshakati|Namibia|-17.788|15.704
Rehoboth|Namibia|-23.317|17.09
Katima Mulilo|Namibia|-17.505|24.276
Otjiwarongo|Namibia|-20.464|16.648
Ondangwa|Namibia|-17.908|15.98
Okahandja|Namibia|-21.981|16.903
Grootfontein|Namibia|-19.573|18.1
Yaren|Nauru|-0.551|166.925
Kathmandu|Nepal|27.702|85.321
Pokhara|Nepal|28.267|83.969
Bharatpur|Nepal|27.68|84.436
Pātan;Patan|Nepal|27.677|85.314
Birgañj;Birganj|Nepal|27.017|84.88
Biratnagar|Nepal|26.455|87.27
Dhangaḍhi̇̄;Dhangadhi|Nepal|28.702|80.59
Hetauda|Nepal|27.428|85.032
Janakpur|Nepal|26.729|85.926
Butwāl;Butwal|Nepal|27.691|83.453
Dharān;Dharan|Nepal|26.814|87.28
Nouméa;Noumea|New Caledonia|-22.274|166.449
Mont-Dore|New Caledonia|-22.263|166.566
Dumbéa;Dumbea|New Caledonia|-22.158|166.457
Auckland|New Zealand|-36.849|174.763
Christchurch|New Zealand|-43.533|172.633
Wellington|New Zealand|-41.287|174.776
Manukau City|New Zealand|-36.993|174.88
Tauranga|New Zealand|-37.686|176.167
Dunedin|New Zealand|-45.874|170.504
Lower Hutt|New Zealand|-41.217|174.917
Palmerston North|New Zealand|-40.356|175.611
New Plymouth|New Zealand|-39.067|174.083
Managua|Nicaragua|12.133|-86.25
Masaya|Nicaragua|11.973|-86.096
Chinandega|Nicaragua|12.63|-87.131
Matagalpa|Nicaragua|12.928|-85.919
Estelí;Esteli|Nicaragua|13.093|-86.356
Mateare|Nicaragua|12.235|-86.428
Jinotega|Nicaragua|13.091|-86.002
El Viejo|Nicaragua|12.663|-87.167
Nueva Guinea|Nicaragua|11.688|-84.456
Niamey|Niger|13.514|2.11
Maradi|Niger|13.5|7.102
Zinder|Niger|13.807|8.988
Tahoua|Niger|14.889|5.269
Agadez|Niger|16.973|7.991
Arlit|Niger|18.737|7.385
Alaghsas|Niger|17.019|8.017
Birni N Konni|Niger|13.796|5.25
Dosso|Niger|13.049|3.194
Tessaoua|Niger|13.757|7.987
Lagos|Nigeria|6.454|3.395
Kano|Nigeria|12|8.517
Ibadan|Nigeria|7.378|3.906
Abuja|Nigeria|9.058|7.495
Port Harcourt|Nigeria|4.777|7.013
Kaduna|Nigeria|10.526|7.439
Benin City|Nigeria|6.338|5.626
Onitsha|Nigeria|6.15|6.786
Aba|Nigeria|5.107|7.367
Maiduguri|Nigeria|11.847|13.157
Ilorin|Nigeria|8.497|4.542
Alofi|Niue|-19.053|-169.92
Pyongyang|North Korea|39.034|125.754
Hamhŭng;Hamhung|North Korea|39.918|127.536
Namp’o;Namp'o|North Korea|38.738|125.408
Sunch’ŏn;Sunch'on|North Korea|39.432|125.933
Hŭngnam;Hungnam|North Korea|39.842|127.632
Kaesŏng;Kaesong|North Korea|37.971|126.554
Wŏnsan;Wonsan|North Korea|39.153|127.444
Chongjin|North Korea|41.796|129.776
Man’gyŏngdae-ri;Man'gyongdae-ri|North Korea|38.992|125.659
Kaech’ŏn;Kaech'on|North Korea|39.701|125.893
Sariwŏn-si;Sariwon-si|North Korea|38.507|125.756
Skopje|North Macedonia|41.996|21.431
Kumanovo|North Macedonia|42.133|21.716
Prilep|North Macedonia|41.346|21.554
Bitola|North Macedonia|41.032|21.336
Čair;Cair|North Macedonia|42.015|21.441
Tetovo|North Macedonia|42.01|20.971
Kisela Voda|North Macedonia|41.949|21.503
Veles|North Macedonia|41.717|21.772
Gostivar|North Macedonia|41.796|20.908
Shtip|North Macedonia|41.746|22.196
Centar Župa;Centar Zupa|North Macedonia|41.478|20.559
Saipan|Northern Mariana Islands|15.212|145.754
Oslo|Norway|59.913|10.746
Bergen|Norway|60.393|5.324
Trondheim|Norway|63.43|10.395
Stavanger|Norway|58.97|5.733
Kristiansand|Norway|58.147|7.996
Drammen|Norway|59.744|10.204
Lillestrøm;Lillestrom|Norway|59.956|11.049
Sandnes|Norway|58.852|5.735
Fredrikstad|Norway|59.218|10.93
Sandefjord|Norway|59.131|10.217
Muscat|Oman|23.584|58.408
Seeb|Oman|23.67|58.189
Bawshar|Oman|23.578|58.4
‘Ibrī;'Ibri|Oman|23.226|56.516
Şalālah;Salalah|Oman|17.015|54.092
Şaḩam;Saham|Oman|24.172|56.889
Rustaq|Oman|23.391|57.424
Sohar|Oman|24.347|56.709
As Suwayq|Oman|23.849|57.439
Samā’il;Sama'il|Oman|23.298|57.953
Al Buraymī;Al Buraymi|Oman|24.251|55.793
Lahore|Pakistan|31.558|74.351
Karachi|Pakistan|24.861|67.01
Peshawar|Pakistan|34.008|71.578
Faisalabad|Pakistan|31.416|73.09
Rawalpindi|Pakistan|33.597|73.048
Gujranwala|Pakistan|32.156|74.187
Multan|Pakistan|30.197|71.478
Quetta|Pakistan|30.184|67.001
Bannu|Pakistan|32.985|70.604
Islamabad|Pakistan|33.721|73.043
Ngerulmud|Palau|7.501|134.624
Gaza|Palestine|31.502|34.467
Khān Yūnis;Khan Yunis|Palestine|31.34|34.306
Jabālyā;Jabalya|Palestine|31.527|34.483
Hebron|Palestine|31.529|35.094
Nablus|Palestine|32.221|35.254
Rafaḩ;Rafah|Palestine|31.297|34.244
Dayr al Balaḩ;Dayr al Balah|Palestine|31.418|34.349
Bayt Lāhyā;Bayt Lahya|Palestine|31.546|34.495
Battir|Palestine|31.7|35.117
Ţūlkarm;Tulkarm|Palestine|32.312|35.027
Panama City|Panama|8.994|-79.52
San Miguelito|Panama|9.05|-79.471
Juan Díaz;Juan Diaz|Panama|9.041|-79.441
Colón|Panama|9.36|-79.9
Arraiján;Arraijan|Panama|8.94|-79.64
La Chorrera|Panama|8.878|-79.78
Tocumen|Panama|9.089|-79.383
Santiago de Veraguas|Panama|8.1|-80.983
Chilibre|Panama|9.154|-79.62
Cativá;Cativa|Panama|9.362|-79.832
Port Moresby|Papua New Guinea|-9.477|147.151
Lae|Papua New Guinea|-6.723|146.996
Arawa|Papua New Guinea|-6.23|155.566
Mount Hagen|Papua New Guinea|-5.857|144.231
Popondetta|Papua New Guinea|-8.765|148.233
Madang|Papua New Guinea|-5.222|145.787
Kokopo|Papua New Guinea|-4.343|152.269
Mendi|Papua New Guinea|-6.148|143.656
Kimbe|Papua New Guinea|-5.551|150.138
Goroka|Papua New Guinea|-6.085|145.387
Wewak|Papua New Guinea|-3.55|143.632
Asunción;Asuncion|Paraguay|-25.286|-57.647
Ciudad del Este|Paraguay|-25.504|-54.651
San Lorenzo|Paraguay|-25.34|-57.509
Capiatá;Capiata|Paraguay|-25.355|-57.445
Lambaré;Lambare|Paraguay|-25.347|-57.606
Fernando de la Mora|Paraguay|-25.339|-57.522
Nemby|Paraguay|-25.395|-57.536
Pedro Juan Caballero|Paraguay|-22.549|-55.739
Encarnación;Encarnacion|Paraguay|-27.332|-55.867
Mariano Roque Alonso|Paraguay|-25.208|-57.532
Lima|Peru|-12.043|-77.028
Callao|Peru|-12.052|-77.135
Arequipa|Peru|-16.399|-71.537
Trujillo|Peru|-8.116|-79.03
Piura|Peru|-5.182|-80.657
Chiclayo|Peru|-6.77|-79.855
Huancayo|Peru|-12.069|-75.21
Cusco|Peru|-13.532|-71.967
Iquitos|Peru|-3.748|-73.253
Pucallpa|Peru|-8.379|-74.554
Chimbote|Peru|-9.075|-78.594
Quezon City|Philippines|14.649|121.051
Davao|Philippines|7.073|125.613
Caloocan|Philippines|14.65|120.968
Manila|Philippines|14.604|120.982
Taguig|Philippines|14.524|121.079
Budta|Philippines|7.204|124.44
Malingao|Philippines|7.161|124.475
Zamboanga|Philippines|6.91|122.074
Cebu City|Philippines|10.317|123.891
Antipolo|Philippines|14.626|121.123
Pasig City|Philippines|14.587|121.061
Adamstown|Pitcairn|-25.066|-130.101
Warsaw|Poland|52.23|21.012
Kraków;Krakow|Poland|50.061|19.937
Wrocław;Wroclaw|Poland|51.103|17.03
Łódź;Lodz|Poland|51.771|19.474
Poznań;Poznan|Poland|52.407|16.93
Gdańsk;Gdansk|Poland|54.352|18.649
Szczecin|Poland|53.429|14.553
Lublin|Poland|51.251|22.57
Bydgoszcz|Poland|53.124|18.008
Białystok;Bialystok|Poland|53.133|23.164
Katowice|Poland|50.26|19.022
Lisbon|Portugal|38.725|-9.15
Porto|Portugal|41.148|-8.611
Braga|Portugal|41.551|-8.423
Amadora|Portugal|38.754|-9.231
Coimbra|Portugal|40.207|-8.42
Leiria|Portugal|39.744|-8.807
Setúbal;Setubal|Portugal|38.524|-8.888
Funchal|Portugal|32.666|-16.925
Viseu|Portugal|40.662|-7.909
Queluz|Portugal|38.757|-9.255
Cacém;Cacem|Portugal|38.767|-9.298
San Juan|Puerto Rico|18.466|-66.106
Bayamón;Bayamon|Puerto Rico|18.399|-66.156
Ponce|Puerto Rico|18.01|-66.624
Arecibo|Puerto Rico|18.472|-66.716
Caguas|Puerto Rico|18.234|-66.048
Guaynabo|Puerto Rico|18.357|-66.111
Trujillo Alto|Puerto Rico|18.355|-66.007
Mayagüez;Mayagueez|Puerto Rico|18.201|-67.14
Fajardo|Puerto Rico|18.326|-65.652
Doha|Qatar|25.285|51.531
Ar Rayyān;Ar Rayyan|Qatar|25.292|51.424
Lusail|Qatar|25.418|51.508
Az̧ Z̧a‘āyin;Az Za'ayin|Qatar|25.577|51.483
Umm Ghuwaylīnah;Umm Ghuwaylinah|Qatar|25.587|51.15
Umm Şalāl Muḩammad;Umm Salal Muhammad|Qatar|25.415|51.406
Mu‘aydhir Rawḑat Rāshid;Mu'aydhir Rawdat Rashid|Qatar|25.262|51.397
Al Wakrah|Qatar|25.172|51.603
Nu‘ayjah;Nu'ayjah|Qatar|25.246|51.532
Al Khawr|Qatar|25.684|51.506
Le Tampon|Reunion|-21.277|55.518
Saint-André;Saint-Andre|Reunion|-20.963|55.65
Saint-Benoît;Saint-Benoit|Reunion|-21.038|55.715
Saint-Leu|Reunion|-21.171|55.288
Bucharest|Romania|44.432|26.106
Iaşi;Iasi|Romania|47.167|27.6
Constanţa;Constanta|Romania|44.181|28.634
Cluj-Napoca|Romania|46.767|23.6
Braşov;Brasov|Romania|45.649|25.606
Timişoara;Timisoara|Romania|45.754|21.226
Craiova|Romania|44.317|23.8
Galaţi;Galati|Romania|45.437|28.05
Târgu Mureş;Targu Mures|Romania|46.542|24.557
Oradea|Romania|47.046|21.918
Ploieşti;Ploiesti|Romania|44.95|26.017
Moscow|Russia|55.752|37.618
Saint Petersburg|Russia|59.939|30.314
Novosibirsk|Russia|55.023|82.932
Yekaterinburg|Russia|56.857|60.615
Nizhniy Novgorod|Russia|56.329|44.002
Kazan|Russia|55.789|49.122
Chelyabinsk|Russia|55.161|61.429
Omsk|Russia|54.992|73.369
Samara|Russia|53.208|50.136
Rostov-on-Don|Russia|47.22|39.708
Ufa|Russia|54.743|55.968
Kigali|Rwanda|-1.95|30.059
Gisenyi|Rwanda|-1.703|29.256
Musanze|Rwanda|-1.5|29.635
Nyagatare|Rwanda|-1.295|30.323
Gitarama|Rwanda|-2.074|29.757
Muhanga|Rwanda|-2.023|29.707
Butare|Rwanda|-2.597|29.739
Kibuye|Rwanda|-2.06|29.348
Rwamagana|Rwanda|-1.949|30.435
Kibungo|Rwanda|-2.16|30.543
Cyangugu|Rwanda|-2.485|28.908
Gustavia|Saint Barthelemy|17.896|-62.85
Basseterre|Saint Kitts and Nevis|17.296|-62.725
Gros Islet|Saint Lucia|14.067|-60.95
Castries|Saint Lucia|13.996|-61.006
Marigot|Saint Martin|18.068|-63.083
Kingstown|Saint Vincent and the Grenadines|13.155|-61.227
Calliaqua|Saint Vincent and the Grenadines|13.129|-61.192
Apia|Samoa|-13.833|-171.767
São Tomé;Sao Tome|Sao Tome and Principe|0.338|6.73
Jeddah|Saudi Arabia|21.49|39.186
Riyadh|Saudi Arabia|24.688|46.722
Makkah|Saudi Arabia|21.427|39.826
Madinah|Saudi Arabia|24.469|39.614
Dammam|Saudi Arabia|26.434|50.103
Sulţānah;Sultanah|Saudi Arabia|24.493|39.586
Buraydah|Saudi Arabia|26.326|43.975
Ta’if;Ta'if|Saudi Arabia|21.27|40.416
Tabuk|Saudi Arabia|28.4|36.572
Ha'il|Saudi Arabia|27.522|41.691
Najrān;Najran|Saudi Arabia|17.493|44.128
Dakar|Senegal|14.694|-17.444
Pikine|Senegal|14.765|-17.391
Touba|Senegal|14.862|-15.875
Guédiawaye;Guediawaye|Senegal|14.774|-17.402
Thiès;Thies|Senegal|14.789|-16.926
Kaolack|Senegal|14.152|-16.073
Rufisque|Senegal|14.715|-17.273
Mbour|Senegal|14.422|-16.964
Saint-Louis|Senegal|16.018|-16.49
Thiès Nones;Thies Nones|Senegal|14.783|-16.967
Ziguinchor|Senegal|12.568|-16.273
Belgrade|Serbia|44.804|20.465
Niš;Nis|Serbia|43.325|21.903
Novi Sad|Serbia|45.252|19.837
Novi Beograd|Serbia|44.806|20.424
Zemun|Serbia|44.846|20.401
Kragujevac|Serbia|44.017|20.917
Čačak;Cacak|Serbia|43.891|20.35
Subotica|Serbia|46.1|19.667
Leskovac|Serbia|42.998|21.946
Novi Pazar|Serbia|43.137|20.512
Kraljevo|Serbia|43.726|20.689
Freetown|Sierra Leone|8.487|-13.236
Kenema|Sierra Leone|7.877|-11.19
Koidu|Sierra Leone|8.644|-10.971
Makeni|Sierra Leone|8.886|-12.044
Port Loko|Sierra Leone|8.766|-12.787
Njala|Sierra Leone|8.232|-12.016
Lunsar|Sierra Leone|8.684|-12.535
Kabala|Sierra Leone|9.589|-11.553
Segbwema|Sierra Leone|7.995|-10.95
Ulu Bedok|Singapore|1.333|103.933
Bedok New Town|Singapore|1.326|103.942
Sengkang New Town|Singapore|1.392|103.894
Jurong Town|Singapore|1.334|103.723
Jurong West|Singapore|1.35|103.723
Yishun New Town|Singapore|1.433|103.831
Punggol|Singapore|1.414|103.907
Choa Chu Kang New Town|Singapore|1.382|103.75
Ang Mo Kio New Town|Singapore|1.38|103.84
Philipsburg|Sint Maarten|18.026|-63.046
Bratislava|Slovakia|48.148|17.107
Košice;Kosice|Slovakia|48.714|21.258
Petržalka;Petrzalka|Slovakia|48.123|17.129
Nitra|Slovakia|48.308|18.085
Prešov;Presov|Slovakia|48.999|21.236
Žilina;Zilina|Slovakia|49.223|18.739
Banská Bystrica;Banska Bystrica|Slovakia|48.739|19.149
Trnava|Slovakia|48.378|17.586
Trenčín;Trencin|Slovakia|48.895|18.044
Poprad|Slovakia|49.061|20.298
Ljubljana|Slovenia|46.051|14.505
Maribor|Slovenia|46.556|15.646
Celje|Slovenia|46.231|15.26
Kranj|Slovenia|46.239|14.356
Koper|Slovenia|45.548|13.73
Novo Mesto|Slovenia|45.804|15.169
Velenje|Slovenia|46.357|15.113
Ptuj|Slovenia|46.42|15.87
Trbovlje|Slovenia|46.154|15.052
Honiara|Solomon Islands|-9.433|159.95
Tandai|Solomon Islands|-9.447|159.945
Malango|Solomon Islands|-9.425|160.053
Mogadishu|Somalia|2.037|45.344
Borama|Somalia|9.936|43.183
Hargeysa|Somalia|9.56|44.065
Berbera|Somalia|10.44|45.014
Kismayo|Somalia|-0.358|42.545
Marka|Somalia|1.716|44.772
El Dibir|Somalia|11.767|51.217
Ruqi|Somalia|9.973|43.428
Baidoa|Somalia|3.114|43.65
Cabudwaaq|Somalia|6.246|46.225
Burao|Somalia|9.522|45.534
Johannesburg|South Africa|-26.202|28.044
Cape Town|South Africa|-33.926|18.423
Durban|South Africa|-29.858|31.029
Pretoria|South Africa|-25.745|28.188
Soweto|South Africa|-26.268|27.858
Gqeberha|South Africa|-33.961|25.615
Soshanguve|South Africa|-25.473|28.099
Pietermaritzburg|South Africa|-29.617|30.393
Evaton|South Africa|-26.533|27.85
Benoni|South Africa|-26.188|28.321
Bloemfontein|South Africa|-29.121|26.214
Grytviken|South Georgia and the South Sandwich Islands|-54.281|-36.509
Seoul|South Korea|37.566|126.978
Busan|South Korea|35.102|129.03
Incheon|South Korea|37.456|126.705
Daegu|South Korea|35.87|128.591
Daejeon|South Korea|36.349|127.385
Gwangju|South Korea|35.155|126.916
Suwon|South Korea|37.291|127.009
Ulsan|South Korea|35.537|129.317
Goyang-si|South Korea|37.656|126.835
Changwon|South Korea|35.228|128.681
Seongnam-si|South Korea|37.439|127.138
Juba|South Sudan|4.852|31.582
Winejok|South Sudan|9.012|27.571
Yei|South Sudan|4.094|30.676
Malakal|South Sudan|9.533|31.66
Wau|South Sudan|7.701|27.99
Kuacjok|South Sudan|8.303|27.98
Pajok|South Sudan|3.865|32.482
Gogrial|South Sudan|8.533|28.1
Yambio|South Sudan|4.571|28.394
Aweil|South Sudan|8.762|27.392
Rumbek|South Sudan|6.806|29.677
Madrid|Spain|40.416|-3.703
Barcelona|Spain|41.389|2.159
Zaragoza|Spain|41.656|-0.877
Sevilla|Spain|37.383|-5.973
Málaga;Malaga|Spain|36.72|-4.42
Murcia|Spain|37.987|-1.13
Palma|Spain|39.569|2.65
Las Palmas de Gran Canaria|Spain|28.102|-15.416
Alicante|Spain|38.345|-0.481
Bilbao|Spain|43.263|-2.925
Colombo|Sri Lanka|6.935|79.849
Dehiwala-Mount Lavinia|Sri Lanka|6.84|79.871
Maharagama|Sri Lanka|6.848|79.926
Jaffna|Sri Lanka|9.668|80.007
Moratuwa|Sri Lanka|6.773|79.882
Negombo|Sri Lanka|7.208|79.836
Pita Kotte|Sri Lanka|6.89|79.902
Sri Jayewardenepura Kotte|Sri Lanka|6.883|79.907
Kandy|Sri Lanka|7.291|80.634
Trincomalee|Sri Lanka|8.578|81.229
Kalmunai|Sri Lanka|7.409|81.835
Khartoum|Sudan|15.552|32.532
Omdurman|Sudan|15.645|32.478
Khartoum North|Sudan|15.649|32.535
Nyala|Sudan|12.049|24.881
Port Sudan|Sudan|19.617|37.216
Kassala|Sudan|15.451|36.4
El Obeid|Sudan|13.184|30.217
Al Qadarif|Sudan|14.035|35.383
Kosti|Sudan|13.163|32.663
Wad Medani|Sudan|14.401|33.52
El Daein|Sudan|11.462|26.126
Paramaribo|Suriname|5.866|-55.167
Lelydorp|Suriname|5.7|-55.233
Longyearbyen|Svalbard and Jan Mayen|78.223|15.647
Stockholm|Sweden|59.329|18.069
Gothenburg|Sweden|57.707|11.967
Malmö;Malmoe|Sweden|55.606|13.001
Uppsala|Sweden|59.859|17.639
Linköping;Linkoeping|Sweden|58.411|15.622
Örebro;OErebro|Sweden|59.274|15.207
Sollentuna|Sweden|59.428|17.951
Umeå;Umea|Sweden|63.828|20.26
Västerås;Vaesteras|Sweden|59.616|16.553
Jönköping;Joenkoeping|Sweden|57.781|14.156
Helsingborg|Sweden|56.047|12.694
Zürich;Zuerich|Switzerland|47.367|8.55
Geneva|Switzerland|46.202|6.146
Basel|Switzerland|47.558|7.573
Lausanne|Switzerland|46.516|6.633
Bern|Switzerland|46.948|7.447
Winterthur|Switzerland|47.506|8.724
Luzern|Switzerland|47.05|8.306
Sankt Gallen|Switzerland|47.424|9.375
Lugano|Switzerland|46.01|8.96
Biel/Bienne|Switzerland|47.137|7.246
Thun|Switzerland|46.751|7.622
Aleppo|Syria|36.201|37.161
Damascus|Syria|33.51|36.291
Homs|Syria|34.724|36.726
Latakia|Syria|35.531|35.791
Ar Raqqah|Syria|35.953|39.008
Ḩamāh;Hamah|Syria|35.132|36.758
Ţarţūs;Tartus|Syria|34.889|35.887
Al Ḩasakah;Al Hasakah|Syria|36.502|40.748
Deir ez-Zor|Syria|35.336|40.141
Al Qāmishlī;Al Qamishli|Syria|37.052|41.231
Al Bāb;Al Bab|Syria|36.371|37.516
Taipei|Taiwan|25.053|121.526
New Taipei City|Taiwan|25.062|121.457
Taichung|Taiwan|24.147|120.684
Kaohsiung|Taiwan|22.616|120.313
Tainan|Taiwan|22.991|120.213
Banqiao|Taiwan|25.014|121.467
Taoyuan|Taiwan|24.994|121.297
Hsinchu|Taiwan|24.804|120.969
Keelung|Taiwan|25.131|121.741
Fengshan|Taiwan|22.627|120.361
Neihu|Taiwan|25.082|121.588
Dushanbe|Tajikistan|38.536|68.779
Isfara|Tajikistan|40.126|70.625
Istaravshan|Tajikistan|39.914|69.003
Kŭlob;Kulob|Tajikistan|37.915|69.785
Konibodom|Tajikistan|40.294|70.431
Khujand|Tajikistan|40.283|69.622
Bokhtar|Tajikistan|37.837|68.778
Qayroqqum|Tajikistan|40.266|69.796
Vahdat|Tajikistan|38.556|69.014
Tursunzoda|Tajikistan|38.513|68.232
Buston|Tajikistan|40.234|69.695
Dar es Salaam|Tanzania|-6.823|39.27
Mwanza|Tanzania|-2.517|32.9
Dodoma|Tanzania|-6.172|35.739
Zanzibar|Tanzania|-6.164|39.198
Arusha|Tanzania|-3.367|36.683
Mbeya|Tanzania|-8.9|33.45
Morogoro|Tanzania|-6.821|37.661
Kahama|Tanzania|-3.833|32.6
Tanga|Tanzania|-5.069|39.099
Geita|Tanzania|-2.872|32.232
Tabora|Tanzania|-5.016|32.827
Bangkok|Thailand|13.754|100.501
Samut Prakan|Thailand|13.598|100.597
Mueang Nonthaburi|Thailand|13.861|100.515
Chon Buri|Thailand|13.362|100.983
Phra Pradaeng|Thailand|13.659|100.534
Bang Khae|Thailand|13.693|100.408
Hat Yai|Thailand|7.008|100.477
Pak Kret|Thailand|13.912|100.498
Sai Mai|Thailand|13.921|100.646
Si Racha|Thailand|13.173|100.932
Watthana|Thailand|13.73|100.585
Rotterdam|The Netherlands|51.922|4.479
Amsterdam|The Netherlands|52.374|4.89
The Hague|The Netherlands|52.077|4.299
Utrecht|The Netherlands|52.091|5.122
Groningen|The Netherlands|53.219|6.567
Eindhoven|The Netherlands|51.441|5.478
Tilburg|The Netherlands|51.556|5.091
Breda|The Netherlands|51.587|4.776
Nijmegen|The Netherlands|51.842|5.853
Almere Stad|The Netherlands|52.37|5.214
Haarlem|The Netherlands|52.381|4.637
Dili|Timor Leste|-8.559|125.574
Maliana|Timor Leste|-8.992|125.22
Suai|Timor Leste|-9.313|125.256
Likisá;Likisa|Timor Leste|-8.588|125.342
Aileu|Timor Leste|-8.728|125.566
Lospalos|Timor Leste|-8.522|126.998
Atsabe|Timor Leste|-8.925|125.398
Maubara|Timor Leste|-8.612|125.206
Venilale|Timor Leste|-8.643|126.378
Baukau|Timor Leste|-8.476|126.456
Lomé;Lome|Togo|6.129|1.222
Sokodé;Sokode|Togo|8.983|1.133
Atakpamé;Atakpame|Togo|7.533|1.133
Kpalimé;Kpalime|Togo|6.9|0.633
Bassar|Togo|9.25|0.782
Dapaong|Togo|10.862|0.208
Tsévié;Tsevie|Togo|6.426|1.213
Aného;Aneho|Togo|6.228|1.592
Anié;Anie|Togo|7.75|1.2
Nuku‘alofa;Nuku'alofa|Tonga|-21.137|-175.201
Chaguanas|Trinidad and Tobago|10.517|-61.417
Mon Repos|Trinidad and Tobago|10.28|-61.446
San Fernando|Trinidad and Tobago|10.28|-61.468
Port of Spain|Trinidad and Tobago|10.667|-61.519
Rio Claro|Trinidad and Tobago|10.306|-61.176
Arima|Trinidad and Tobago|10.637|-61.282
Marabella|Trinidad and Tobago|10.306|-61.447
Diego Martin|Trinidad and Tobago|10.721|-61.566
Laventille|Trinidad and Tobago|10.649|-61.499
Point Fortin|Trinidad and Tobago|10.174|-61.684
Tunapuna|Trinidad and Tobago|10.652|-61.389
Tunis|Tunisia|36.819|10.166
Sfax|Tunisia|34.741|10.76
Sousse|Tunisia|35.825|10.637
Sukrah|Tunisia|36.877|10.247
Kairouan|Tunisia|35.678|10.096
Bizerte|Tunisia|37.274|9.874
Sīdī Ḥusayn;Sidi Husayn|Tunisia|36.756|10.118
Sakiet ed Daier|Tunisia|34.794|10.806
El Mourouj|Tunisia|36.714|10.21
Aryanah|Tunisia|36.86|10.193
Gabès;Gabes|Tunisia|33.881|10.098
Istanbul|Turkey|41.014|28.95
Ankara|Turkey|39.92|32.854
Bursa|Turkey|40.196|29.06
İzmir;Izmir|Turkey|38.413|27.138
Gaziantep|Turkey|37.059|37.382
Diyarbakır;Diyarbakir|Turkey|37.914|40.217
Adana|Turkey|36.986|35.325
Kayseri|Turkey|38.732|35.485
Konya|Turkey|37.871|32.485
Antalya|Turkey|36.908|30.696
Esenyurt|Turkey|41.027|28.677
Ashgabat|Turkmenistan|37.95|58.383
Türkmenabat;Tuerkmenabat|Turkmenistan|39.073|63.579
Daşoguz;Dasoguz|Turkmenistan|41.836|59.967
Türkmenbaşy;Tuerkmenbasy|Turkmenistan|40.022|52.955
Balkanabat|Turkmenistan|39.511|54.367
Bayramaly|Turkmenistan|37.619|62.167
Tejen|Turkmenistan|37.383|60.505
Gyzylarbat|Turkmenistan|38.976|56.276
Magdanly|Turkmenistan|37.812|66.047
Boldumsaz|Turkmenistan|42.128|59.672
Providenciales|Turks and Caicos Islands|21.783|-72.252
Cockburn Town|Turks and Caicos Islands|21.461|-71.142
Funafuti|Tuvalu|-8.524|179.194
Saint Croix|U.S. Virgin Islands|17.728|-64.747
Charlotte Amalie|U.S. Virgin Islands|18.342|-64.931
Dubai|UAE|25.077|55.309
Abu Dhabi|UAE|24.451|54.397
Sharjah|UAE|25.334|55.412
Al Ain City|UAE|24.192|55.761
Ajman|UAE|25.402|55.479
Ras Al Khaimah|UAE|25.79|55.943
Musaffah|UAE|24.359|54.483
Jebel Ali|UAE|25.003|55.108
Fujairah|UAE|25.116|56.341
Warīsān;Warisan|UAE|25.167|55.407
Khalifah A City|UAE|24.426|54.605
Kampala|Uganda|0.316|32.582
Nansana|Uganda|0.364|32.529
Bunamwaya|Uganda|0.253|32.557
Kyengera|Uganda|0.295|32.502
Mbarara|Uganda|-0.605|30.649
Kasangati|Uganda|0.438|32.602
Mukono|Uganda|0.353|32.755
Njeru|Uganda|0.442|33.179
Gulu|Uganda|2.775|32.299
Katabi|Uganda|0.084|32.47
London|UK|51.509|-0.126
Birmingham|UK|52.481|-1.9
Glasgow|UK|55.865|-4.258
Manchester|UK|53.481|-2.237
Sheffield|UK|53.383|-1.466
Leeds|UK|53.796|-1.548
Edinburgh|UK|55.952|-3.196
Liverpool|UK|53.411|-2.978
Bristol|UK|51.455|-2.597
Cardiff|UK|51.48|-3.18
Leicester|UK|52.639|-1.132
Kyiv|Ukraine|50.455|30.524
Kharkiv|Ukraine|49.982|36.255
Odesa|Ukraine|46.486|30.744
Dnipro|Ukraine|48.467|35.041
Donetsk|Ukraine|48.023|37.802
Lviv|Ukraine|49.838|24.023
Zaporizhzhya|Ukraine|47.852|35.117
Kryvyy Rih|Ukraine|47.906|33.394
Sevastopol|Ukraine|44.608|33.521
Mykolayiv|Ukraine|46.976|31.993
Vinnytsya|Ukraine|49.232|28.469
Montevideo|Uruguay|-34.903|-56.188
Salto|Uruguay|-31.388|-57.96
Maldonado|Uruguay|-34.898|-54.95
Paysandú;Paysandu|Uruguay|-32.317|-58.081
Las Piedras|Uruguay|-34.73|-56.219
Tacuarembó;Tacuarembo|Uruguay|-31.719|-55.979
Artigas|Uruguay|-30.404|-56.469
Durazno|Uruguay|-33.381|-56.523
New York City|USA|40.714|-74.006
Los Angeles|USA|34.052|-118.244
Brooklyn|USA|40.65|-73.95
Chicago|USA|41.85|-87.65
Houston|USA|29.763|-95.363
Phoenix|USA|33.448|-112.074
Philadelphia|USA|39.952|-75.164
San Antonio|USA|29.424|-98.494
Manhattan|USA|40.783|-73.966
Tashkent|Uzbekistan|41.265|69.216
Andijon|Uzbekistan|40.783|72.351
Namangan|Uzbekistan|40.998|71.673
Samarkand|Uzbekistan|39.655|66.964
Nukus|Uzbekistan|42.459|59.606
Fergana|Uzbekistan|40.384|71.784
Bukhara|Uzbekistan|39.77|64.431
Qarshi|Uzbekistan|38.861|65.789
Qo‘qon;Qo'qon|Uzbekistan|40.529|70.942
Marg‘ilon;Marg'ilon|Uzbekistan|40.472|71.725
Angren|Uzbekistan|41.017|70.144
Port-Vila|Vanuatu|-17.736|168.314
Vatican City|Vatican|41.903|12.454
Caracas|Venezuela|10.488|-66.879
Maracaibo|Venezuela|10.642|-71.611
Barquisimeto|Venezuela|10.065|-69.357
Ciudad Guayana|Venezuela|8.351|-62.641
Maturín;Maturin|Venezuela|9.746|-63.183
Maracay|Venezuela|10.25|-67.595
Ciudad Bolívar;Ciudad Bolivar|Venezuela|8.124|-63.547
Cumaná;Cumana|Venezuela|10.464|-64.179
Barinas|Venezuela|8.621|-70.231
Ho Chi Minh City|Vietnam|10.823|106.63
Hanoi|Vietnam|21.024|105.841
Haiphong|Vietnam|20.865|106.683
Cần Thơ;Can Tho|Vietnam|10.037|105.788
Huế;Hue|Vietnam|16.462|107.595
Da Nang|Vietnam|16.068|108.221
Biên Hòa;Bien Hoa|Vietnam|10.945|106.824
Thanh Hóa;Thanh Hoa|Vietnam|19.8|105.767
Vinh|Vietnam|18.673|105.692
Thuận An;Thuan An|Vietnam|10.924|106.714
Nha Trang|Vietnam|12.245|109.194
Mata-Utu|Wallis and Futuna|-13.282|-176.175
Laayoune|Western Sahara|27.142|-13.188
Dakhla|Western Sahara|23.685|-15.958
Boujdour|Western Sahara|26.131|-14.485
El Marsa|Western Sahara|27.096|-13.416
Sanaa|Yemen|15.355|44.206
Aden|Yemen|12.78|45.039
Taiz|Yemen|13.58|44.021
Ibb|Yemen|13.967|44.183
Al Ḩudaydah;Al Hudaydah|Yemen|14.798|42.955
Mukalla|Yemen|14.542|49.124
Dhamār;Dhamar|Yemen|14.543|44.405
‘Amrān;'Amran|Yemen|15.659|43.944
Sayyān;Sayyan|Yemen|15.172|44.324
Zabīd;Zabid|Yemen|14.195|43.315
Sa'dah|Yemen|16.94|43.764
Lusaka|Zambia|-15.407|28.287
Kitwe|Zambia|-12.802|28.213
Ndola|Zambia|-12.959|28.637
Chipata|Zambia|-13.633|32.65
Solwezi|Zambia|-12.169|26.389
Kabwe|Zambia|-14.447|28.446
Chingola|Zambia|-12.529|27.884
Luanshya|Zambia|-13.137|28.417
Kasama|Zambia|-10.213|31.181
Mansa|Zambia|-11.2|28.894
Harare|Zimbabwe|-17.828|31.053
Bulawayo|Zimbabwe|-20.15|28.583
Chitungwiza|Zimbabwe|-18.013|31.076
Mutare|Zimbabwe|-18.971|32.671
Gweru|Zimbabwe|-19.45|29.817
Kwekwe|Zimbabwe|-18.928|29.815
Kadoma|Zimbabwe|-18.333|29.915
Ruwa|Zimbabwe|-17.89|31.245
Chinhoyi|Zimbabwe|-17.367|30.2
Masvingo|Zimbabwe|-20.064|30.828
`;
