// Generated by scripts/build-provinces.ps1 from Natural Earth admin-1 label points (public domain).
// First-level regions for 21 countries common in conflict and disaster news. Same format as PLACE_LINES,
// all regions; a leading "~" marks a name that only counts with a suffix ("Rivers State", "Fars province").
// cities.js and places.js take priority when a name appears there too.
const PROVINCE_LINES = `
Acre State;~Acre|Brazil|-8.928|-70.298
Alagoas State;Alagoas|Brazil|-9.774|-36.692
Amapá State;Amapá;Amapa|Brazil|1.412|-51.684
Amazonas State;~Amazonas;Amazone|Brazil|-4.218|-63.785
Bahia State;Bahia|Brazil|-12.365|-41.803
Ceará State;Ceará;Ceara|Brazil|-5.376|-39.343
Espírito Santo State;Espírito Santo;Espirito Santo;Espiritu Santo|Brazil|-19.692|-40.544
~Federal|Brazil|-15.766|-47.79
Goiás State;Goiás;Goias;Goiáz;Goiaz;Goyáz;Goyaz|Brazil|-15.863|-49.579
Maranhão State;Maranhão;Maranhao;São Luíz de Maranhão;Sao Luiz de Maranhao|Brazil|-5.019|-45.389
Mato Grosso do Sul State;Mato Grosso do Sul|Brazil|-20.676|-54.55
Mato Grosso State;Mato Grosso;Matto Grosso|Brazil|-13.393|-55.924
Minas Gerais State;Minas Gerais;Minas;Minas Geraes|Brazil|-18.59|-44.481
Pará State;~Pará;~Para|Brazil|-4.443|-52.649
Paraíba State;Paraíba;Paraiba;Parahyba|Brazil|-7.342|-36.273
Paraná State;Paraná;Parana|Brazil|-24.662|-51.323
Pernambuco State;Pernambuco;Pernambouc|Brazil|-8.473|-37.296
Piauí State;Piauí;Piaui;Piauhy|Brazil|-8.087|-43.197
Rio de Janeiro State;Rio de Janeiro|Brazil|-22.405|-43.115
Rio Grande do Norte State;Rio Grande do Norte|Brazil|-5.662|-36.547
Rio Grande do Sul State;Rio Grande do Sul|Brazil|-29.728|-53.656
Rondônia State;Rondônia;Rondonia;Guaporé;Guapore|Brazil|-10.971|-63.144
Roraima State;Roraima;Rio Branco|Brazil|1.938|-61.332
Santa Catarina State;~Santa Catarina;Santa Catharina|Brazil|-27.039|-51.159
São Paulo State;São Paulo;Sao Paulo|Brazil|-22.227|-48.521
Sergipe State;Sergipe|Brazil|-10.592|-37.384
Tocantins State;Tocantins|Brazil|-10.223|-48.25
Anhui Province;Anhui;Ānhuī|China|31.954|117.253
Fujian Province;Fujian;Fújiàn|China|26.408|118.178
Gansu Province;Gansu;Gānsù|China|38.739|100.735
Guangdong Province;Guangdong;Guǎngdōng|China|23.792|113.72
Guangxi;Guangxi Zhuang;Guangxi Zhuàngzú;Guangxi Zhuangzu|China|23.745|108.756
Guizhou Province;Guizhou;Gùizhōu|China|26.803|106.559
Hainan Province;Hainan;Hǎinán|China|19.186|109.825
Hebei Province;~Hebei;Héběi|China|38.52|115.314
Heilongjiang Province;Heilongjiang;Hēilóngjiāng|China|46.845|127.97
Henan Province;~Henan;Hénán|China|33.906|113.484
Hubei Province;~Hubei;Húběi|China|30.986|112.264
Hunan Province;~Hunan;Húnán|China|27.667|111.712
Inner Mongolia;Inner Mongol;Nei Mongol;Nèiměnggǔ;Neimenggu|China|41.594|111.623
Jiangsu Province;Jiangsu;Jiāngsū|China|32.984|119.942
Jiangxi Province;Jiangxi;Jiāngxī|China|27.64|116.017
Jilin Province;~Jilin;Jílín|China|43.298|126.466
Liaoning Province;Liaoning;Liáoníng|China|41.386|123.07
Ningxia;Ningxia Hui;Níngxià Húizú;Ningxia Huizu|China|37.176|106.038
Paracel Islands|China|15.783|111.201
Qinghai Province;Qinghai|China|35.265|96.238
Shaanxi Province;Shaanxi;Shǎnxī|China|33.771|108.363
Shandong Province;Shandong;Shāndōng|China|36.327|118.114
Shanxi Province;Shānxī|China|37.759|112.389
Sichuan Province;Sichuan;Sìchuān|China|30.543|102.384
Tibet;Xizang;Xīzàng|China|31.452|88.414
Xinjiang;Xinjiang Uygur;Xīnjiāng Wéiwúěr;Xinjiang Weiwuer|China|41.122|85.425
Yunnan Province;Yunnan;Yúnnán|China|24.46|101.661
Zhejiang Province;Zhejiang;Zhèjiāng|China|29.108|119.97
Bandundu Province;Bandundu|DR Congo|-4.618|18.447
Équateur Province;Équateur;Equateur;Equator;Equatorial|DR Congo|1.218|20.473
Kasaï-Occidental Province;Kasaï-Occidental;Kasai-Occidental;Kasai West;West Kasai;West Kassai|DR Congo|-4.876|21.714
Kasaï-Oriental Province;Kasaï-Oriental;Kasai-Oriental;East Kasai;Kasai East|DR Congo|-4.405|24.084
Katanga Province;Katanga;Shaba|DR Congo|-8.484|26.251
Kongo Central Province;Bas-Congo;Kongo Central;Bas-Zaire;Bas-Zaïre;Kongo-Central;Lower Zaire|DR Congo|-5.319|14.205
Maniema Province;Maniema|DR Congo|-3.26|26.034
North Kivu Province;Nord-Kivu;North Kivu|DR Congo|-0.659|28.594
Orientale Province;Orientale;Haut-Zaire;Haut-ZaïreUpper Zaire;Haut-ZaireUpper Zaire|DR Congo|2.404|26.785
South Kivu Province;Sud-Kivu;South Kivu;Sud-Kivou;Sud Kivou;Sud Kivu|DR Congo|-3.105|28.116
Addis Ababa;Āddīs Ābaba;Addis Abeba;Adis-Abeba;Ādīs Ābeba;Adis Abeba|Ethiopia|8.966|38.782
~Afar|Ethiopia|12.123|41.024
Amhara;Amara|Ethiopia|11.698|37.722
Benishangul-Gumuz;Benshangul-Gumaz;Benishangul;Beni Shangul;Bénishangul;Binshangul Gumuz|Ethiopia|10.54|35.602
Dire Dawa|Ethiopia|9.562|42.036
~Gambela;Gambela Peoples;Gambella;Gambela Hizboch|Ethiopia|7.869|34.178
~Harari;Harari People;Harer;Hareri Hizb|Ethiopia|9.291|42.168
Oromia;Oromiya|Ethiopia|7.556|40.224
~Somali;Sumale|Ethiopia|7.094|43.534
Southern Nations|Ethiopia|6.215|36.449
Tigray;Tigrai;Tigre;Tigré|Ethiopia|14.1|38.216
Andaman and Nicobar Islands;Andaman and Nicobar;Andaman et Nicobar;Iihas de Andama e Nicobar;Inseln Andamanen und Nikobare|India|6.837|93.79
Andhra Pradesh State;Andhra Pradesh|India|16.485|79.208
Arunachal Pradesh State;Arunachal Pradesh;North East Frontier Agency|India|28.406|94.467
Assam State;Assam|India|26.33|92.993
Bihar State;Bihar|India|25.685|85.813
Chandigarh|India|30.745|76.76
Chhattisgarh State;Chhattisgarh|India|21.804|82.307
Dadra and Nagar Haveli and Daman and Diu;DAdra et Nagar Haveli;Dadra e Nagar Haveli;Dadra and Nagar Haveli|India|20.184|73.029
Daman and Diu|India|20.423|72.851
Delhi|India|28.69|77.086
Goa State|India|15.313|73.995
Gujarat|India|22.75|71.301
Haryana State;Haryana|India|29.1|76.271
Himachal Pradesh|India|31.676|77.288
Jammu and Kashmir|India|33.966|76.64
Jharkhand State;Jharkhand;Vananchal|India|23.522|85.058
Karnataka State;Karnataka;Maisur;Mysore|India|14.368|75.667
Kerala State;Kerala|India|10.367|76.524
Ladakh|India|34.026|77.481
Lakshadweep;Íles Laquedives;Iles Laquedives;Laccadive;Minicoy and Amindivi Islands;Laccadives;Lackadiverna;Lakkadiven;Lakkadi|India|11.225|72.781
Madhya Pradesh State;Madhya Pradesh|India|22.94|78.421
Maharashtra State;Maharashtra|India|19.472|75.465
Manipur State;Manipur|India|24.744|93.846
Meghalaya State;Meghalaya|India|25.48|91.303
Mizoram State;Mizoram|India|23.204|92.841
Nagaland State;Nagaland|India|26.109|94.566
Odisha State;Odisha;Orissa|India|20.625|84.434
Puducherry;Pondicherry;Puduchcheri;Pondichéry;Pondichery|India|10.922|79.776
Punjab State|India|31.024|75.376
Rajasthan State;Rajasthan;Greater Rajasthan;Rajputana|India|26.747|73.856
Sikkim State;Sikkim|India|27.571|88.448
Tamil Nadu State;Tamil Nadu|India|11.016|78.27
Telangana State;Telangana|India|17.427|78.468
Tripura State;Tripura|India|23.852|91.703
Uttar Pradesh State;Uttar Pradesh;United Provinces|India|26.72|80.997
Uttarakhand State;Uttarakhand;Uttaranchal|India|30.058|79.284
West Bengal State;West Bengal;Bangla;Bengala Occidentale;Bengala Ocidental;Bengale occidental|India|23.052|87.729
Alborz Province;Alborz|Iran|35.965|50.785
Ardabil Province;Ardebil;Ardabil|Iran|38.911|47.724
Bushehr Province;Bushehr;Banader va Jazayer-e Khalij-e Fars;Bushire;Persian Gulf;Ports and Islands of the Persian Gulf|Iran|28.827|51.422
Chaharmahal and Bakhtiari Province;Chahar Mahall and Bakhtiari;Chaharmahal and Bakhtiari;Bakhtiari;Chaharmahal va Bakhtiyari;Charmahal-Bakhtiyari|Iran|31.998|50.53
East Azerbaijan Province;East Azarbaijan;East Azerbaijan;Azarbayjan-e Khavari;Azarbaijan-e Sharghi;Azarbaijan-Sharqi;East Azarbayejan|Iran|37.85|46.772
Fars Province;~Fars|Iran|29.401|53.079
Gilan Province;Gilan|Iran|37.05|49.516
Golestan Province;Golestan|Iran|37.312|55.004
Hamadan Province;Hamadan;Hamedan|Iran|34.834|48.574
Hormozgan Province;Hormozgan;Banader va Jazayer-e Bahr-e Oman;Ports and Islands of the Sea of Oman;Saheli|Iran|27.646|56.25
Ilam Province;Ilam;Ilam and Poshtkuh|Iran|33.237|46.812
Isfahan Province;Esfahan;Isfahan;Ispahan|Iran|32.984|52.42
Kerman Province;Kerman|Iran|30.123|56.957
Kermanshah Province;Kermanshah;Bakhtaran;Kermanshahan|Iran|34.28|46.689
Khuzestan Province;Khuzestan;Khuzistan;Kouzistan|Iran|31.348|48.756
Kohgiluyeh and Boyer-Ahmad Province;Kohgiluyeh and Buyer Ahmad;Kohgiluyeh and Boyer-Ahmad;Bovir Ahmadi and Kohkiluyeh;Boyer-Ahmad and Koh-Giluye;Boyer Ahmad e Kohkiluyeh;Boyer Ahmadi-ye Sardir va Kohkiluyeh;Kohgil|Iran|30.698|50.795
Kurdistan Province;Kordestan;~Kurdistan|Iran|35.578|46.864
Lorestan Province;Lorestan|Iran|33.532|48.414
Markazi Province;Markazi|Iran|34.56|49.964
Mazandaran Province;Mazandaran|Iran|36.231|52.212
North Khorasan Province;North Khorasan;Khorasan-e Shemali|Iran|37.579|57.048
Qazvin Province;Qazvin|Iran|36.055|49.7
Qom Province|Iran|34.666|50.978
Razavi Khorasan Province;Razavi Khorasan;Khorasan-e Razavi|Iran|35.584|58.798
Semnan Province;Semnan|Iran|35.424|54.438
Sistan and Baluchestan Province;Sistan and Baluchestan;Baluchestan va Sistan;Seistan and Baluchistan;Sistan e Baloutchistan|Iran|27.427|61.047
South Khorasan Province;South Khorasan;Khorasan-e Janubi|Iran|32.456|59.489
Tehran Province;Tehran;Teheran|Iran|35.515|51.655
West Azerbaijan Province;West Azarbaijan;West Azerbaijan;Azarbayjan-e Bakhtari;Azarbaijan-e Gharbi;West Azarbayejan|Iran|36.667|45.673
Yazd Province;Yazd|Iran|32.707|55.524
Zanjan Province;Zanjan|Iran|36.399|48.296
Al Anbar Province;Al-Anbar;Al Anbar;Dulaim;Ramadi|Iraq|33.232|41.531
Al Muthanna Province;Al-Muthannia;Al Muthanna;Al-Muthanna|Iraq|30.438|45.284
Al-Qādisiyyah Province;Al-Qādisiyyah;Al-Qadisiyyah;Diwaniyah|Iraq|31.608|45.108
Babylon Province;Babil;Babylon;Hilla|Iraq|32.683|44.51
Baghdad Province;Baghdad;Bagd;Bagdad|Iraq|33.306|44.383
Basra Province;Al-Basrah;Basra;Bassora|Iraq|30.68|47.56
Dhi Qar Province;Dhi-Qar;Dhi Qar;Muntafiq;Nasiriyah;Thi-Qar|Iraq|31.191|46.42
Diyala Province;Diyala|Iraq|33.988|45.105
Duhok Province;Dihok;Duhok;Dahuk;D'hok|Iraq|37.088|43.228
Erbil Province;Arbil;Erbil;Arbela;Irbil|Iraq|36.237|44.181
Karbala Province;Karbala';Karbala;Kerbela|Iraq|32.502|43.765
Kirkuk Province;At-Ta'mim;Kirkuk;Tamin|Iraq|35.328|44.035
Maysan Province;Maysan|Iraq|31.809|47.074
Najaf Province;An-Najaf;Najaf|Iraq|30.932|43.755
Nineveh Province;Ninawa;Nineveh;Al-Mawsil;Mosul;Ninive;Niniveh|Iraq|35.923|42.747
Saladin Province;Sala ad-Din;Saladin;Salah ad-Din;Salaheddin|Iraq|34.342|43.729
Sulaymaniyah Province;As-Sulaymaniyah;Sulaymaniyah|Iraq|35.332|45.433
Wasit Province;Wasit;Kut-al-Imara|Iraq|32.614|45.564
Central District;HaMerkaz|Israel|31.907|34.849
Haifa District;Haifa;Hefa|Israel|32.552|34.973
Jerusalem District;~Jerusalem;Al-Quds;Yerushalayim|Israel|31.74|35.018
Northern District;HaZafon|Israel|32.824|35.42
Southern District;HaDarom;~Southern|Israel|30.935|34.842
Tel Aviv District;Tel Aviv|Israel|32.097|34.809
Beirut Province;Beirut;Bayrut;Beirute;Beyrouth|Lebanon|33.885|35.509
Beqaa Province;Beqaa;Bekaa;El Begaa;Béqaa;La Bekaa|Lebanon|34.049|36.109
Mount Lebanon Province;~Mount Lebanon;Jabal Lubnan;Mont-Liban|Lebanon|33.929|35.694
Nabatieh Province;An Nabatiyah;Nabatieh;Nabatîyé;Nabatiye|Lebanon|33.33|35.567
North Province;North Lebanon;~North;Ash Shamal;Liban-Nord|Lebanon|34.393|36.042
South Province;South Lebanon;~South;Al Janub;Liban-Sud;Sayda|Lebanon|33.266|35.297
Aguascalientes State;Aguascalientes|Mexico|22.038|-102.351
Baja California State;Baja California|Mexico|30.34|-115.209
Baja California Sur State;Baja California Sur|Mexico|25.066|-111.452
Campeche State;Campeche|Mexico|18.662|-90.281
Chiapas State;Chiapas|Mexico|16.527|-92.581
Chihuahua State;Chihuahua|Mexico|28.973|-106.232
Coahuila State;Coahuila|Mexico|27.447|-101.885
Colima State;Colima|Mexico|19.132|-103.915
Durango State;~Durango|Mexico|24.566|-104.808
Guanajuato State;Guanajuato|Mexico|20.814|-100.904
Guerrero State;~Guerrero|Mexico|17.761|-100.091
Hidalgo State;~Hidalgo|Mexico|20.535|-98.922
Jalisco State;Jalisco|Mexico|20.303|-103.602
Mexico State;~México;State of Mexico|Mexico|19.328|-99.742
Michoacán State;Michoacán;Michoacan|Mexico|19.246|-101.936
Morelos State;~Morelos|Mexico|18.742|-99.078
Nayarit State;Nayarit|Mexico|21.793|-104.824
Nuevo León State;Nuevo León;Nuevo Leon|Mexico|25.618|-99.831
Oaxaca State;Oaxaca|Mexico|16.94|-96.209
Puebla State;Puebla|Mexico|18.549|-97.889
Querétaro State;Querétaro;Queretaro|Mexico|20.739|-99.966
Quintana Roo State;Quintana Roo|Mexico|19.386|-88.344
San Luis Potosí State;San Luis Potosí;San Luis Potosi|Mexico|22.446|-100.324
Sinaloa State;Sinaloa|Mexico|25.604|-108.001
Sonora State;Sonora|Mexico|29.529|-110.485
Tabasco State;~Tabasco|Mexico|18.125|-92.827
Tamaulipas State;Tamaulipas|Mexico|24.081|-98.52
Tlaxcala State;Tlaxcala|Mexico|19.396|-98.161
Veracruz State;Veracruz|Mexico|19.093|-96.595
Yucatán State;Yucatán;Yucatan|Mexico|20.663|-88.984
Zacatecas State;Zacatecas|Mexico|23.378|-102.579
Ayeyarwady;Irrawaddy;Ayeyarwaddy;Ayeyawady;Irawadi;Irraouaddi;Irrauaddy|Myanmar|16.746|95.108
Bago;Pégou;Pegou;Pegu|Myanmar|18.518|96.148
Chin State;~Chin;Chin Hills|Myanmar|21.926|93.373
Kachin State;Kachin;Jingphaw Mungdaw|Myanmar|25.793|97.298
Kayah State;~Kayah;Karenni|Myanmar|19.266|97.353
Kayin State;Kayin;Kawthulei;~Karen;Karin;Kawthoolei;Kawthulay|Myanmar|17.4|97.651
Magway;Magwe;Minbu|Myanmar|19.647|94.881
Mandalay|Myanmar|20.628|96.061
Mon State|Myanmar|16.304|97.806
Rakhine State;Rakhine;Arakan|Myanmar|20.275|93.64
Sagaing|Myanmar|23.703|95.182
Shan State;~Shan|Myanmar|21.518|98.159
Tanintharyi;Tenasserim;Thanintharyi|Myanmar|13.612|98.775
Yangon;Rangoon;Rangum;Rangun|Myanmar|17.112|96.111
Abia State;Abia|Nigeria|5.574|7.56
Adamawa State;Adamawa|Nigeria|9.479|12.577
Akwa Ibom State;Akwa Ibom|Nigeria|4.899|7.91
Anambra State;Anambra|Nigeria|6.308|6.985
Bauchi State;Bauchi|Nigeria|10.41|9.886
Bayelsa State;Bayelsa|Nigeria|4.739|5.974
Benue State;Benue|Nigeria|7.487|8.707
Borno State;Borno|Nigeria|12.002|13.153
Cross River State;Cross River|Nigeria|5.938|8.679
Delta State;~Delta|Nigeria|5.443|5.882
Ebonyi State;Ebonyi|Nigeria|6.326|7.983
Edo State|Nigeria|6.524|5.849
Ekiti State;~Ekiti|Nigeria|7.671|5.359
Enugu State;Enugu|Nigeria|6.554|7.384
Federal Capital State;Federal Capital;Abuja|Nigeria|8.789|7.189
Gombe State;Gombe|Nigeria|10.434|11.242
Imo State|Nigeria|5.55|7.016
Jigawa State;Jigawa|Nigeria|12.071|9.362
Kaduna State;Kaduna|Nigeria|10.329|7.439
Kano State;Kano|Nigeria|11.732|8.541
Katsina State;Katsina|Nigeria|12.506|7.586
Kebbi State;Kebbi|Nigeria|11.771|4.065
Kogi State;~Kogi|Nigeria|7.785|6.614
Kwara State;Kwara|Nigeria|8.804|4.469
Lagos State;~Lagos|Nigeria|6.433|3.525
Nasarawa State;Nassarawa;Nasarawa|Nigeria|8.504|8.277
Niger State;~Niger|Nigeria|9.956|5.455
Ogun State;~Ogun|Nigeria|7.018|3.293
Ondo State;~Ondo|Nigeria|7.144|5.192
Osun State;Osun|Nigeria|7.476|4.549
Oyo State|Nigeria|8.19|3.617
Plateau State;~Plateau|Nigeria|8.953|9.606
Rivers State;~Rivers|Nigeria|4.998|6.82
Sokoto State;Sokoto|Nigeria|13.06|5.437
Taraba State;Taraba|Nigeria|7.936|10.543
Yobe State;Yobe|Nigeria|12.316|11.588
Zamfara State;Zamfara|Nigeria|12.008|6.128
Azad Kashmir;Kashmir|Pakistan|33.868|73.804
Balochistan Province;Baluchistan;Balochistan;BéloutchistanBeluchistan;BeloutchistanBeluchistan;Baluchistão;Baluchistao|Pakistan|27.519|65.551
Federally Administered Tribal Areas;F.A.T.A.|Pakistan|32.615|69.898
Gilgit-Baltistan;Northern Areas|Pakistan|35.786|74.985
Islamabad Capital;F.C.T.;Islamabad Capital Territory;Islamabad;Federal Capital Territory Islamabad;Territoire de la Capitale fédérale;Territoire de la Capitale federale|Pakistan|33.701|73.063
Khyber Pakhtunkhwa Province;K.P.;Khyber Pakhtunkhwa;North-West Frontier Province|Pakistan|34.941|72.64
Punjab Province;Pendjab;Penjab|Pakistan|31.359|72.345
Sindh Province;Sind;Sindh|Pakistan|26.373|68.868
Gaza;Gaza Strip|Palestine|31.426|34.365
West Bank|Palestine|32.003|35.292
Adygea Republic;Adygey;Republic of Adygea;Adygea;Adygeya;Adygheya;Republic of Adygeya;Adygeyskaya A.Obl.;Respublika Adygeya|Russia|44.466|40.129
Altay;Altayskiy Kray|Russia|52.427|82.867
Gorno-Altay;Gorno-Altayskaya A.Obl.;Respublika Altay;Oirot;Republic of Altai|Russia|50.978|86.937
Amur Region;Amur;Amurskaya Oblast|Russia|52.924|128.354
Arkhangelsk Region;Arkhangel'sk;Arkhangelsk|Russia|63.313|41.994
Astrakhan Region;Astrakhan';Astrakhan;Astrachan;Astrakhanskaya Oblast|Russia|47.033|47.723
Autonomous Republic of Crimea;Crimea;Crimée;Crimee;Criméia;Crimeia;Krim;Krymskaya Respublika;Respublika Krym|Russia|45.312|34.278
Bashkortostan Republic;Bashkortostan;Bashkir;Bashkiriya;Bashkirskaya A.S.S.R.;Republic of Bashkortostan;Respublika Bashkortostan|Russia|54.209|56.558
Belgorod Region;Belgorod;Belgorodskaya Oblast|Russia|50.876|37.277
Bryansk Region;Bryansk;Bryanskaya Oblast|Russia|53.087|33.28
Buryatia Republic;Buryat;Republic of Buryatia;Buryatia;Buryatiya;Buryat-Mongol A.S.S.R.;Buryatskaya A.S.S.R.|Russia|52.906|109.341
Chechen Republic;Chechnya;Chechen;Cecenia;Chechenia;Chechênia;Tchetchnia;Chechen-Ingush A.S.S.R.;Checheno-Ingushetia|Russia|43.215|45.757
Chelyabinsk Region;Chelyabinsk;Chelyabinskaya|Russia|54.113|60.238
Chukchi Autonomous Okrug;Chukotka Autonomous Okrug;Chukchi;Chukotskiy Avtonomnyy Okrug|Russia|66.752|170.516
Chuvash Republic;Chuvash;Chuvashskaya A.S.S.R.;Chuvashskaya Respublika;Chuvashiya|Russia|55.488|47.166
Dagestan Republic;Dagestan;Republic of Dagestan;Dagestanskaya A.S.S.R.;Daghestan;Respublika Dagestan;Dagistan|Russia|42.36|47.142
Ingushetia Republic;Ingush;Republic of Ingushetia;Ingushetia;Ingouchie;Inguchétia;Inguchetia;Inguschetien;Ingushetiya;Ingush Republic;Ingushskaya Respublika;Respublika Ingushetiya|Russia|43.366|44.847
Irkutsk Region;Irkutsk;Irkutskaya Oblast|Russia|56.826|105.966
Ivanovo Region;Ivanovo;Ivanovskaya Oblast|Russia|57.121|41.624
Jewish;Yevrey;Den jødiske autonome oblasten;Evrey;Jewish A.Obl.;Yahudi;Yevreyskaya A.Obl.;Evreyskaya AOb|Russia|48.64|132.758
Kabardino-Balkaria Republic;Kabardin-Balkar;Kabardino-Balkaria;Kabardin A.S.S.R.;Kabardino-Balkarskaya A.S.S.R.;Kabardino-Balkariya;Kabardino-Balkarsk;Kabard;Kabardino-Balkarskaya Republic|Russia|43.376|43.398
Kaliningrad Region;Kaliningrad;Kaliningradskaya Oblast|Russia|54.664|21.229
Kalmykia Republic;Kalmyk;Republic of Kalmykia;Kalmykia;Kalmykiya;Khalmg Tangch;Kalmytskaya A.S.S.R.;Respublika Kalmykiya|Russia|46.519|45.468
Kaluga Region;Kaluga;Kaluzhskaya Oblast|Russia|54.242|35.342
Kamchatka Region;Kamchatka;Kamchatka Krai;Kamçatka;Kamcatka;Kamchatskaya Oblast|Russia|56.532|160.187
Karachay-Cherkess Republic;Karachay-Cherkess;Karaçay-Çerkes;Karacay-Cerkes;Karachay-Cherkessiya;Karachayevo-Cherkesskaya Respublika;Karachayevo-Cherkessiya;Karachayevo-Cherkess Republic|Russia|43.707|41.687
Karelia Republic;Karelia;Karelian A.S.S.R.;Karelo-Finnish A.S.S.R.;Karel'skaya A.S.S.R.;Olonets;Olonetskaya G.;Kareliya;Republic of Karelia|Russia|63.53|33.145
Kemerovo Region;Kemerovo;Kemerovskaya Oblast|Russia|54.646|87.168
Khabarovsk;Khabarovsk Krai;Khabarovskiy Kray|Russia|57.023|135.443
Khakassia Republic;Khakass;Republic of Khakassia;Khakassia;Khakassiya;Republic of Khakasia;Khakasskaya A.Obl.;Respublika Khakasiya|Russia|53.364|89.84
Khanty-Mansi;Khanty-Mansiy;Khanty-Mansi Autonomous Okrug;Khanty-Mansiysk;Khanty-Mansiyskiy A.Okr.;Khanty-Mansiyskiy A.Okr.-Yugra;Khanty-Mansiyskiy AOk|Russia|61.432|71.381
Kirov Region;Kirov;Vyatka;Vyatskaya G.;Kirovskaya Oblast|Russia|58.193|50.111
Komi Republic;Komi;Komi A.S.S.R.;Republic of Komi;Respublika Komi|Russia|64.119|55.818
Kostroma Region;Kostroma;Kostromskaya|Russia|58.388|43.469
Krasnodar;Krasnodar Krai;Cossacks of the Black Sea;Kuban;Kubanskaya;Yekaterinodar;Krasnodarskiy Kray|Russia|45.84|39.469
Krasnoyarsk;Krasnoyarsk Krai;Krasnoyarskiy Kray;Yeniseisk;Yeniseyskaya G.|Russia|65.56|95.203
Kurgan Region;Kurgan;Kurganskaya Oblast|Russia|55.432|65.35
Kursk Region;Kursk;Kurskaya Oblast|Russia|51.736|36.292
Leningrad Region;Leningrad;Saint Petersburg;Sankt-Peterburgskaya G.;Leningradskaya Oblast|Russia|59.99|32.774
Lipetsk Region;Lipetsk;Lipetskaya Oblast|Russia|52.746|39.207
Magadan Region;Maga Buryatdan;Magadan;Magadanskaya Oblast|Russia|62.626|153.797
Mari El Republic;Mariy-El;Mari El;Mari;Mari-El;Republic of Mari El;Mariyskaya A.S.S.R.;Respublika Mariy El|Russia|56.541|47.913
Mordovia Republic;Mordovia;Republic of Mordovia;Mordov;Mordvian Autonomous Republic;Mordvinia;Mordovian A.S.S.R.|Russia|54.115|44.463
Moscow Region;Moskovskaya;Moscow;Moskovskaya Oblast|Russia|55.151|38.671
Murmansk Region;Murmansk;Murmanskaya Oblast|Russia|67.961|34.321
Nenets;Nenets Autonomous Okrug;Nenetskiy A.Okr.;Nenetskiy AOk|Russia|67.827|56.288
Nizhny Novgorod Region;Nizhegorod;Nizhny Novgorod;Gor'kiy;Gor'kovskaya;Gorky;Nizhegorodskaya;Nizhniy-Novgorod|Russia|56.138|44.775
North Ossetia-Alania Republic;North Ossetia;Republic of North Ossetia-Alania;North Ossetia-Alania;Kuzey Osetya;Respublika Severnaya Osetiya;Severnaya Osetiya-Alaniya;North Ossetian A.S.S.R.;Republic of North Osetia-Alania|Russia|42.997|44.165
Novgorod Region;Novgorod;Novgorodskaya Oblast|Russia|58.423|32.945
Novosibirsk Region;Novosibirsk;Novosibirskaya Oblast|Russia|55.314|80.083
Omsk Region;Omsk;Omskaya Oblast|Russia|56.047|73.4
Orenburg Region;Orenburg;Chkalov;Orenburgskaya;Orenburgskaya Oblast|Russia|51.516|56.215
Oryol Region;Orel;Oryol;Orlovskaya;Or'ol;Orlovskaya Oblast|Russia|52.878|36.417
Penza Region;Penza;Penzenskaya Oblast|Russia|53.056|44.816
Perm;Perm';Perm Krai;Molotov;Permskaya Oblast|Russia|58.874|56.588
Primorsky;Primor'ye;Primorsky Krai;Küsten-Gebiet;Kusten-Gebiet;Maritime Territory;Primorsk;Primorskiy Kray|Russia|44.862|134.594
Pskov Region;Pskov;Pskovskaya Oblast|Russia|57.245|29.123
Rostov Region;Rostov;Province of the Don Cossacks;Provinz des Donischen Heeres;Voyska Donskovo;Rostovskaya Oblast|Russia|47.991|41.261
Ryazan Region;Ryazan';Ryazan;Ryazanskaya Oblast|Russia|54.336|40.626
Sakha;Sakha Republic;Chukotskiy AOk|Russia|65.596|130.989
Sakhalin Region;Sakhalin;Sakhalinskaya Oblast|Russia|47.348|152.467
Samara Region;Samara;Kuybyshev;Kuybyshevskaya;Samarskaya Oblast|Russia|53.178|50.438
Saratov Region;Saratov;Saratovskaya Oblast|Russia|51.674|46.637
Smolensk Region;Smolensk;Smolenskaya Oblast|Russia|54.673|33.08
Stavropol;Stavropol';Stavropol Krai;Stavropol'skiy Kray;Stavropolskiy Kray|Russia|44.981|43.279
Sverdlovsk Region;Sverdlovsk;Yekaterinburg;Sverdlovskaya Oblast|Russia|58.895|61.708
Tambov Region;Tambov;Tambovskaya Oblast|Russia|52.781|41.594
Tatarstan Republic;Tatarstan;Republic of Tatarstan;Kazan;Kazanskaya G.;Tatar A.S.S.R.;Tatarskaya A.S.S.R.;Respublika Tatars|Russia|55.374|50.736
Tomsk Region;Tomsk;Tomskaya|Russia|58.447|82.23
Tula Region;Tula;Tul'skaya;Tulskaya Oblast|Russia|54.067|37.416
Tuva Republic;Tuva;Respublika Tyva;Republic of Tuva;Tyva;Tuvinskaya A.S.S.R.;Republic of Tyva|Russia|51.605|93.993
Tver Region;Tver';Tver;Kalinin;Kalininskaya;Tverskaya Oblast|Russia|57.03|34.544
Tyumen Region;Tyumen';Tyumen;Tobol'sk;Tobol'skaya G.;Tyumenskaya Oblast|Russia|57.264|68.519
Udmurt Republic;Udmurt;Udmurtiya;Udmurtskaya A.S.S.R.;Udmurtskaya Respublika|Russia|57.343|52.796
Ulyanovsk Region;Ul'yanovsk;Ulyanovsk;Simbirsk;Simbirskaya G.;Ul'yanovskaya Oblast|Russia|53.925|47.377
Vladimir Region;Vladimir;Vladimirskaya|Russia|55.897|40.621
Volgograd Region;Volgograd;Stalingrad;Volgogradskaya Oblast|Russia|49.501|44.449
Vologda Region;Vologda|Russia|59.64|40.933
Voronezh Region;Voronezh;Voronezhskaya Oblast|Russia|50.777|40.522
Yamalo-Nenets;Yamal-Nenets;Yamalo-Nenets Autonomous Okrug;Yamalo-Nenetskiy A.Okr|Russia|65.412|75.187
Yaroslavl Region;Yaroslavl';Yaroslavl;Yaroslavskaya Oblast|Russia|57.733|39.255
Zabaykalsky Region;Chita;Zabaykalsky Krai;Zabaykalsky;Transbaikalia;Zabaykal'skaya;Transbaikalien;Chitinskaya Oblast|Russia|52.159|116.559
Bakool Region;Bakool|Somalia|4.406|43.835
Banaadir Region;Banaadir;Benadir|Somalia|2.124|45.436
Bari Region;~Bari|Somalia|9.956|50.178
Bay Region;Baay|Somalia|2.672|43.545
Galguduud Region;Galguduud;Galgudug|Somalia|5.096|46.68
Gedo Region;Gedo;Gado|Somalia|3.054|42.052
Hiran Region;Hiiraan;Hiran;Hiiran|Somalia|4.368|45.498
Lower Juba Region;Jubbada Hoose;Lower Juba;J. Hoose|Somalia|0.008|41.809
Lower Shebelle Region;Shabeellaha Hoose;Lower Shebelle;Sh. Hoose;Lower Shabele|Somalia|1.636|44.185
Middle Juba Region;Jubbada Dhexe;Middle Juba;J. Dhexe;Central Juba|Somalia|1.553|42.471
Middle Shebelle Region;Shabeellaha Dhexe;Middle Shebelle;Sh. Dhexe;Central Shabele|Somalia|3.006|46.055
Mudug Region;Mudug;Madugh;Mudugh|Somalia|5.51|48.101
Nugal Region;Nugaal;Nugal|Somalia|8.461|48.849
Al Jazirah State;Gezira;Al Jazirah|Sudan|14.677|33.336
Al Qadarif State;Gedarif;Al Qadarif;Gadarif;Gedaref;Gederaf|Sudan|14.028|35.035
Blue Nile State;Blue Nile;An Nīl al Azraq;Nil Bleu;Nilo Azul|Sudan|11.166|34.116
Central Darfur State;Central Darfur|Sudan|12.198|23.347
East Darfur State;Eastern Darfur;East Darfur|Sudan|11.026|26.53
Kassala State;Kassala;Cassala;Kessala|Sudan|15.626|35.598
Khartoum Region;Khartoum;Al Kharţūm;Al Khartum;Al Khurţūm;Al Khurtum;Cartum;Jartum;Khartum|Sudan|15.734|32.982
North Darfur State;North Darfur;Darfur ash Shamaliyah;Shamal Darfur;Darfur septentrional|Sudan|16.46|25.506
North Kordofan State;North Kordufan;North Kordofan;Kordofan septentrional;Kurdufān ash Shamālīyah;Kurdufan ash Shamaliyah;Shamāl Kurdufān;Shamal Kurdufan|Sudan|14.53|29.612
Northern State|Sudan|19.315|28.833
Red Sea State;~Red Sea;Mar Rojo;Mar Rosso;Mar Vermelho;Mer Rouge;Röda havet;Roda havet;Rødehavet;Rotes Meer|Sudan|19.529|35.887
River Nile State;River Nile;Nile;Nile River;Nilen;Nilo|Sudan|17.558|33.762
Sennar Region;~Sennar|Sudan|13.21|34.252
South Darfur State;South Darfur|Sudan|11.369|24.596
South Kordofan State;South Kordufan;South Kordofan;Southern Kordofan;Janūb Kurdufān;Janub Kurdufan;Janub Kurdufun;Kurdufān al Janūbīyah;Kurdufan al Janubiyah;Kordofan méridional;Kordofan meridional|Sudan|11.45|29.83
West Soudan State;Western Darfur;West Soudan|Sudan|14.211|23.086
White Nile State;White Nile;An Baḥr al Abyad;An Bahr al Abyad;An Nīl al-Abyad;An Nil al-Abyad;Nil Blanc;Nilo Branco|Sudan|13.595|32.363
Aleppo Province;Aleppo;Alep;Alepo;Haleb;Ḥalab;Halab|Syria|36.105|37.601
Al-Hasakah Province;Al-Hasakah;Al Hasaka;Al-Haska;Al Hassake;El Haseke;Haseke;Hassakeh;Hazakieh;Hassetché;Hassetche;Al Jezira;Jezireh|Syria|36.354|40.909
Al-Raqqah Province;Ar Raqqah;Al-Raqqah;Al Rakka;Raqqa;Al Rashid;Rashid|Syria|36.007|38.913
As-Suwayda Province;As Suwayda';As-Suwayda;Djebel Druze;Jabal Druze;Jebel Druse;Jebel ed Druz;Al Sueida;Es Sueida;Es Suweida;Soueida;Suwaidaa|Syria|32.758|36.915
Damascus Province;Damascus|Syria|33.51|36.29
Daraa Province;Dar'a;Daraa;Dara'a;Dária;Daria;Dera'a;Derraa;Hauran|Syria|32.869|36.17
Deir ez-Zor Province;Dayr Az Zawr;Deir ez-Zor;Dair-Ezzor;Dayr az Zaur;Deir Al Zour;Deir ez Zor;Der Azzor;Dier Elzour|Syria|35.074|40.275
Hama Province;Hamah;Hama;Ḥamāh|Syria|35.235|37.22
Homs Province;Homs;Hims|Syria|34.15|38.142
Idlib Province;Idlib;Adlib;Edleb;Idleb|Syria|35.853|36.683
Latakia Province;Lattakia;Latakia;Al Ladhiqiyah;El Ladhiqiya;Lattakieh;Lattikia;Lattaquie|Syria|35.549|36.006
Quneitra Province;Quneitra;Al Qunatirah;Al Qunaytirah;Al Quneitera;El Quneitra;El Kenitra;Kunaitra;Kuneitra;Qunaytira|Syria|33.053|35.914
Rif Dimashq Province;Rif Dimashq|Syria|33.529|37.073
Tartus Province;Tartus;Tartaus;Tartous|Syria|34.927|36.09
Western al-Samadania;UNDOF|Syria|33.151|35.862
Adana Province;Adana;Seyhan|Turkey|37.401|35.756
Adıyaman Province;Adiyaman;Adıyaman|Turkey|37.81|38.339
Afyonkarahisar Province;Afyonkarahisar;Afyon|Turkey|38.678|30.694
Ağrı Province;Agri;Ağrı;Agrı;Ağri;Karaköse;Karakose|Turkey|39.592|43.365
Aksaray Province;Aksaray|Turkey|38.357|33.877
Amasya Province;Amasya|Turkey|40.638|35.763
Ankara Province;Ankara;Ancara;Angora|Turkey|39.829|32.578
Antalya Province;Antalya;Adalia;Anatolia|Turkey|37.114|30.956
Ardahan Province;Ardahan|Turkey|41.181|42.834
Artvin Province;Artvin;Çoruh;Coruh|Turkey|41.018|41.833
Aydın Province;Aydin;Aydın|Turkey|37.729|27.957
Balıkesir Province;Balikesir;Balıkesir;Balikisri|Turkey|39.719|27.836
Bartın Province;Bartın|Turkey|41.586|32.469
Batman Province;~Batman|Turkey|37.734|41.426
Bayburt Province;Bayburt|Turkey|40.286|40.306
Bilecik Province;Bilecik|Turkey|40.039|30.2
Bingöl Province;Bingöl;Bingol;Çapakçur;Capakcur|Turkey|39.074|40.646
Bitlis Province;Bitlis|Turkey|38.516|42.346
Bolu Province;~Bolu|Turkey|40.585|31.681
Burdur Province;Burdur|Turkey|37.5|30.163
Bursa Province;Bursa;Burssa;Brusa;Brussa;Brousse|Turkey|40.131|29.059
Çanakkale Province;Çanakkale;Canakkale|Turkey|40.055|26.823
Çankırı Province;Çankiri;Cankiri;Çankırı;Cankırı;Changra|Turkey|40.709|33.214
Çorum Province;Çorum;Corum|Turkey|40.615|34.711
Denizli Province;Denizli|Turkey|37.754|29.282
Diyarbakır Province;Diyarbakir;Diyarbakır|Turkey|38.026|40.271
Düzce Province;Düzce;Duzce|Turkey|40.863|31.323
Edirne Province;Edirne;Adrianople;Adrianopel|Turkey|40.958|26.47
Elazığ Province;Elazig;Elazığ;Elazıg|Turkey|38.572|39.37
Erzincan Province;Erzincan|Turkey|39.687|39.512
Erzurum Province;Erzurum|Turkey|39.968|41.403
Eskişehir Province;Eskisehir;Eskişehir|Turkey|39.63|31.089
Gaziantep Province;Gaziantep|Turkey|36.999|37.246
Giresun Province;Giresun;Kerasund|Turkey|40.538|38.606
Gümüşhane Province;Gümüshane;Gumushane;Gümüşhane|Turkey|40.281|39.354
Hakkâri Province;Hakkari;Hakkâri|Turkey|37.61|44.08
Hatay Province;Hatay|Turkey|36.488|36.228
Iğdır Province;Iğdir;Igdir;Iğdır;Igdır|Turkey|39.811|44.032
Isparta Province;Isparta|Turkey|37.892|30.818
Istanbul Province;Istanbul;İstanbul;Constantinople;Estambul;Istambul;Konstantinopel;Stamboul|Turkey|41.128|28.846
İzmir Province;Izmir;İzmir;Esmirna;Smirne;Smyrna|Turkey|38.243|27.398
Kahramanmaraş Province;K. Maras;Kahramanmaraş;Kahramanmaras|Turkey|37.928|37.001
Karabük Province;Karabük;Karabuk|Turkey|41.235|32.507
Karaman Province;Karaman|Turkey|37.226|33.303
Kars Province;~Kars|Turkey|40.367|43.074
Kastamonu Province;Kastamonu|Turkey|41.511|33.636
Kayseri Province;Kayseri|Turkey|38.717|35.926
Kilis Province;Kilis|Turkey|36.833|37.004
Kırıkkale Province;Kinkkale;Kırıkkale|Turkey|39.901|33.778
Kırklareli Province;Kirklareli;Kırklareli|Turkey|41.62|27.492
Kırşehir Province;Kirsehir;Kırşehir;Kırsehir|Turkey|39.355|34.131
Kocaeli Province;Kocaeli;İzmit;Izmit|Turkey|40.901|29.94
Konya Province;Konya;Konieh;Kunja|Turkey|38.04|32.469
Kütahya Province;Kütahya;Kutahya;Kütanya;Kutanya|Turkey|39.347|29.55
Malatya Province;Malatya|Turkey|38.514|38.187
Manisa Province;Manisa|Turkey|38.712|28.132
Mardin Province;Mardin|Turkey|37.428|40.952
Mersin Province;Mersin;İçel;Icel|Turkey|36.661|33.827
Muğla Province;Mugla;Muğla|Turkey|37.05|28.648
Muş Province|Turkey|38.912|41.903
Nevşehir Province;Nevsehir;Nevşehir|Turkey|38.742|34.641
Niğde Province;Nigde;Niğde|Turkey|37.897|34.709
Ordu Province;~Ordu|Turkey|40.838|37.423
Osmaniye Province;Osmaniye|Turkey|37.174|36.301
Rize Province;~Rize|Turkey|40.947|40.869
Sakarya Province;Sakarya|Turkey|40.66|30.444
Samsun Province;Samsun|Turkey|41.276|36.02
Şanlıurfa Province;Sanliurfa;Şanlıurfa;Sanlıurfa;Urfa|Turkey|37.319|39.051
Siirt Province;Siirt|Turkey|37.916|42.221
Sinop Province;Sinop|Turkey|41.589|34.823
Şırnak Province;Sirnak;Şırnak;Sırnak|Turkey|37.405|42.546
Sivas Province;Sivas|Turkey|39.429|37.291
Tekirdağ Province;Tekirdag;Tekirdağ|Turkey|41.082|27.455
Tokat Province;Tokat|Turkey|40.444|36.572
Trabzon Province;Trabzon;Trapezunt;Trebizond;Trebizonda;Trébizonde;Trebizonde|Turkey|40.799|39.803
Tunceli Province;Tunceli|Turkey|39.152|39.636
Uşak Province;Usak;Uşak|Turkey|38.494|29.364
Van Province|Turkey|38.521|43.568
Yalova Province;Yalova|Turkey|40.615|29.204
Yozgat Province;Yozgat|Turkey|39.548|35.133
Zonguldak Province;Zinguldak;Zonguldak|Turkey|41.248|31.821
Cherkasy Region;Cherkasy;Cherkas'ka Oblast';Cherkasskaya Oblast';Cherkassy|Ukraine|49.151|31.224
Chernihiv Region;Chernihiv;Chernigov;Tschernigow|Ukraine|51.26|32.029
Chernivtsi Region;Chernivtsi;Chernivets'ka Oblast';Chernovitskaya Oblast';Chernovtsy;Czernowitz;Tschernowzy;Tchernovtsy|Ukraine|48.289|26.216
Dnipropetrovsk Region;Dnipropetrovs'k;Dnipropetrovsk;Dniepropietrovsk;Dnjepropetrowsk|Ukraine|48.631|34.956
Donetsk Region;Donets'k;Donetsk;Donetskaya Oblast';Donezk;Stalino|Ukraine|48.145|37.793
Ivano-Frankivsk Region;Ivano-Frankivs'k;Ivano-Frankivsk;Ivano-Frankovsk;Ivano-Frankovskaya Oblast';Stanislav|Ukraine|48.665|24.636
Kharkiv Region;Kharkiv;Charkow;Jarkov;Karkov;Khar'kov|Ukraine|49.466|36.461
Kherson|Ukraine|46.696|33.579
Khmelnytskyi Region;Khmel'nyts'kyy;Khmelnytskyi;Khmelnitsky;Chmelnizkij;Hmelnicki;Kamenets-Podol'skaya Oblast';Khmel'nyts'ka Oblast'|Ukraine|49.554|27.019
Kirovohrad Region;Kirovohrad;Kirovograd;Kirovogradskaya Oblast'|Ukraine|48.426|31.829
Kyiv Region;Kiev;Kyiv;Kiev Oblast;Kiew;Kijew;Kiiv;Kijev;Kiyev;Kyjiv;Kyyiv;Kyyivs'ka Oblast'|Ukraine|50.089|31.021
Luhansk Region;Luhans'k;Luhansk;Lugansk;Luhans'ka Oblast';Voroshilovgrad|Ukraine|48.908|39.003
Lviv Region;L'viv;Lviv;Lemberg;Llvov;L'vov;Lwow;L'vivs'ka Oblast'|Ukraine|49.815|24.037
Mykolaiv Region;Mykolayiv;Mykolaiv;Nikolajew;Nikolayev|Ukraine|47.09|31.65
Odessa Region;Odessa;Odesa;Odes'ka Oblast';Odesskaya Oblast'|Ukraine|46.032|29.757
Poltava Region;Poltava|Ukraine|49.698|33.772
Rivne Region;Rivne;Rovno;Rivnens'ka Oblast';Rovenskaya Oblast'|Ukraine|51.048|26.384
Sumy Region;Sumy|Ukraine|50.815|34.316
Ternopil Region;Ternopil';Ternopil;Ternopol;Ternopol'|Ukraine|49.474|25.544
Vinnytsia Region;Vinnytsya;Vinnytsia;Vinnitskaya Oblast';Vinnyts'ka Oblast;Winniza|Ukraine|48.962|28.723
Volyn Region;Volyn;Volhynia;Volyns'ka Oblast';Volynskaya Oblast';Wolynien|Ukraine|51.125|24.844
Zakarpattia Region;Transcarpathia;Zakarpattia;Transcarpathian;Ruthenia;Zakarpats'ka Oblast';Zakarpatskaya Oblast'|Ukraine|48.363|23.387
Zaporizhzhia Region;Zaporizhzhya;Zaporizhzhia;Saporoshje;Zaporizhia;Zaporiz'ka Oblast';Zaporojie;Zaporozhskaya Oblast';Zaporozh'ye;Zaporožje;Zaporozje|Ukraine|47.335|35.712
Zhytomyr Region;Zhytomyr;Zhitomir;Jitomir;Shitomir;Zhitomirskaya Oblast'|Ukraine|50.69|28.464
Abyan Governorate;Abyan|Yemen|13.827|46.212
Ad Dali' Governorate;Al Dali';Ad Dali';Al Dhale'e|Yemen|13.896|44.794
'Adan Governorate;Aden|Yemen|12.809|44.754
Al Bayda' Governorate;Al Bayda';Albaidah;Al Baidha;Al-Baydha;Al Beida;Baidaa;Al Bayda|Yemen|14.29|45.337
Al Hudaydah Governorate;Al Hudaydah;Al Hodeida;Al-Hodeidah;Al Hudaidah;Hodiedah;Hudaidah|Yemen|14.928|43.221
Al Jawf Governorate;Al Jawf;Al Jouf;Aljowf;Jawf|Yemen|16.563|45.614
Al Mahrah Governorate;Al Mahrah;Al Ghaydah;Al-Mahara;Almaharah;al-Mahra;Mahra|Yemen|16.878|51.641
Al Mahwit Governorate;Al Mahwit;Almahweet;Mahweet|Yemen|15.38|43.649
'Amran Governorate;Amran|Yemen|16.094|44.011
Dhamar Governorate;Dhamar|Yemen|14.68|44.2
Hadhramaut Governorate;Hadramawt;Hadhramaut;Hadhramawt;Hadhramout;HadramautHadramout|Yemen|16.378|48.913
Hajjah Governorate;Hajjah;Hajja|Yemen|16.181|43.18
Ibb Governorate|Yemen|14.054|44.201
Lahij Governorate;Lahij;Laheg;Lahej;Lahj;Tuban|Yemen|13.183|44.656
Ma'rib Governorate;Ma'rib;Mareb;Marib|Yemen|15.537|45.738
Raymah Governorate;Raymah|Yemen|14.666|43.758
Sa'dah Governorate;Sa'dah;Sa'ada;Saadah;Sa'da;Saidah;Sa'adah|Yemen|16.988|44.04
Amanat Al Asimah|Yemen|15.349|44.212
Sana'a|Yemen|15.226|44.368
Shabwah Governorate;Shabwah;Shabwa;Shibwah;Ataq|Yemen|14.896|47.099
Ta'izz Governorate;Ta'izz;Taez;Taiz;Taizz|Yemen|13.428|43.73
`;
