param([string]$Data, [string]$Skip = "$PSScriptRoot\city-skip.txt", [string]$Out = "$PSScriptRoot\..\cities.js")
# Builds cities.js: every country's capital plus its 10 largest other cities, from GeoNames cities15000.
# Usage: download cities15000.zip (unzipped) and countryInfo.txt from https://download.geonames.org/export/dump/
# into a folder, then: powershell -File scripts\build-cities.ps1 -Data <that folder>
# Names it leaves out (too short, in city-skip.txt, a country's name, or a duplicate) go to <that folder>\dropped.txt.
$ErrorActionPreference = "Stop"
$dir = $Data
$utf8 = [Text.UTF8Encoding]::new($false)

# Display names that match the rest of the site.
$rename = @{
  "United States" = "USA"; "United Kingdom" = "UK"; "United Arab Emirates" = "UAE";
  "Democratic Republic of the Congo" = "DR Congo"; "Republic of the Congo" = "Congo";
  "Palestinian Territory" = "Palestine"; "Czechia" = "Czechia"; "Ivory Coast" = "Ivory Coast";
  "Bosnia and Herzegovina" = "Bosnia"; "Central African Republic" = "Central African Republic";
}

$countries = @{}
$countryNames = New-Object 'System.Collections.Generic.HashSet[string]'
foreach ($line in [IO.File]::ReadAllLines("$dir\countryInfo.txt", $utf8)) {
  if ($line.StartsWith("#") -or -not $line.Trim()) { continue }
  $f = $line.Split("`t")
  $name = $f[4]
  if ($rename.ContainsKey($name)) { $name = $rename[$name] }
  $countries[$f[0]] = $name
  [void]$countryNames.Add($f[4]); [void]$countryNames.Add($name)
}

$skipSet = New-Object 'System.Collections.Generic.HashSet[string]'
foreach ($s in [IO.File]::ReadAllLines($Skip, $utf8)) { $t = $s.Trim(); if ($t -and -not $t.StartsWith("#")) { [void]$skipSet.Add($t) } }

$bad = @("PPLX", "PPLH", "PPLQ", "PPLW", "PPLCH")
$byCountry = @{}
foreach ($line in [IO.File]::ReadLines("$dir\cities15000.txt", $utf8)) {
  $f = $line.Split("`t")
  if ($bad -contains $f[7]) { continue }
  $row = [pscustomobject]@{ name = $f[1]; ascii = $f[2]; lat = [double]$f[4]; lng = [double]$f[5]; code = $f[7]; cc = $f[8]; pop = [long]$f[14] }
  if (-not $byCountry.ContainsKey($row.cc)) { $byCountry[$row.cc] = New-Object System.Collections.ArrayList }
  [void]$byCountry[$row.cc].Add($row)
}

$picked = New-Object System.Collections.ArrayList
foreach ($cc in $byCountry.Keys) {
  if (-not $countries.ContainsKey($cc)) { continue }
  $rows = $byCountry[$cc] | Sort-Object pop -Descending
  $capital = $rows | Where-Object { $_.code -eq "PPLC" } | Select-Object -First 1
  $others = $rows | Where-Object { $_ -ne $capital } | Select-Object -First 10
  foreach ($r in @($capital) + @($others)) {
    if ($r) { [void]$picked.Add([pscustomobject]@{ row = $r; country = $countries[$cc]; capital = ($r -eq $capital) }) }
  }
}

# One entry per name: the more populous city keeps it.
$byName = @{}
$dropped = New-Object System.Collections.ArrayList
foreach ($p in ($picked | Sort-Object { $_.row.pop } -Descending)) {
  # A backtick would end the JavaScript template string, so it becomes an apostrophe.
  $tick = [string][char]96
  $names = @($p.row.name.Replace($tick, "'"))
  $ascii = $p.row.ascii.Replace($tick, "'")
  if ($ascii -and $ascii -ne $names[0]) { $names += $ascii }
  $keep = @()
  foreach ($n in $names) {
    if ($n.Length -lt 3) { [void]$dropped.Add("short: $n ($($p.country))"); continue }
    if ($skipSet.Contains($n)) { [void]$dropped.Add("word: $n ($($p.country))"); continue }
    if ($countryNames.Contains($n)) { [void]$dropped.Add("country name: $n ($($p.country))"); continue }
    if ($byName.ContainsKey($n)) { [void]$dropped.Add("duplicate: $n ($($p.country)) kept for $($byName[$n])"); continue }
    $keep += $n
  }
  if (-not $keep.Count) { continue }
  foreach ($n in $keep) { $byName[$n] = $p.country }
  $p | Add-Member names $keep
}

$lines = $picked | Where-Object { $_.names } | Sort-Object country, { -$_.row.pop } | ForEach-Object {
  $n = ($_.names -join ";")
  "{0}|{1}|{2}|{3}" -f $n, $_.country, [Math]::Round($_.row.lat, 3).ToString([Globalization.CultureInfo]::InvariantCulture), [Math]::Round($_.row.lng, 3).ToString([Globalization.CultureInfo]::InvariantCulture)
}
$header = @"
// Generated by scripts/build-cities.ps1 from GeoNames (https://www.geonames.org, CC BY 4.0):
// each country's capital plus its 10 largest other cities. Same format as PLACE_LINES in places.js,
// which takes priority when a name appears in both. Edit places.js by hand; regenerate this file.
const CITY_LINES = ``
"@
[IO.File]::WriteAllText($Out, $header + "`n" + ($lines -join "`n") + "`n``;`n", $utf8)
[IO.File]::WriteAllLines("$dir\dropped.txt", $dropped, $utf8)
"cities: $($lines.Count)  dropped names: $($dropped.Count)"

